/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";
import { GetActionStatusResponseDataCollection } from "./GetActionStatusResponseDataCollection";
import { GetActionStatusResponseDataRecipient } from "./GetActionStatusResponseDataRecipient";
import { GetActionStatusResponseDataToken } from "./GetActionStatusResponseDataToken";

export const GetActionStatusResponseData: core.serialization.ObjectSchema<
    serializers.GetActionStatusResponseData.Raw,
    Crossmint.GetActionStatusResponseData
> = core.serialization.object({
    collection: GetActionStatusResponseDataCollection.optional(),
    recipient: GetActionStatusResponseDataRecipient.optional(),
    token: GetActionStatusResponseDataToken.optional(),
});

export declare namespace GetActionStatusResponseData {
    interface Raw {
        collection?: GetActionStatusResponseDataCollection.Raw | null;
        recipient?: GetActionStatusResponseDataRecipient.Raw | null;
        token?: GetActionStatusResponseDataToken.Raw | null;
    }
}
