/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";
import { GetActionStatusResponseData } from "./GetActionStatusResponseData";

export const GetActionStatusResponse: core.serialization.ObjectSchema<
    serializers.GetActionStatusResponse.Raw,
    Crossmint.GetActionStatusResponse
> = core.serialization.object({
    actionId: core.serialization.string().optional(),
    action: core.serialization.string().optional(),
    status: core.serialization.string().optional(),
    data: GetActionStatusResponseData.optional(),
    startedAt: core.serialization.date().optional(),
    resource: core.serialization.string().optional(),
});

export declare namespace GetActionStatusResponse {
    interface Raw {
        actionId?: string | null;
        action?: string | null;
        status?: string | null;
        data?: GetActionStatusResponseData.Raw | null;
        startedAt?: string | null;
        resource?: string | null;
    }
}
