/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";

export const GetActionStatusResponseDataRecipient: core.serialization.ObjectSchema<
    serializers.GetActionStatusResponseDataRecipient.Raw,
    Crossmint.GetActionStatusResponseDataRecipient
> = core.serialization.object({
    walletAddress: core.serialization.string().optional(),
});

export declare namespace GetActionStatusResponseDataRecipient {
    interface Raw {
        walletAddress?: string | null;
    }
}
