/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../../../../index";

/**
 * @example
 *     {
 *         nfts: [{}]
 *     }
 */
export interface BatchMintNftRequest {
    /** Array of objects describing the NFTs to mint to recipients. */
    nfts: Crossmint.BatchMintNftRequestNftsItem[];
}
