/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../../../../index";

/**
 * @example
 *     {
 *         metadata: {
 *             name: "Crossmint Example NFT",
 *             image: "https://www.crossmint.com/assets/crossmint/logo.png",
 *             description: "My NFT created via the mint API!"
 *         },
 *         reuploadLinkedFiles: true
 *     }
 */
export interface EditNftByLocatorRequest {
    metadata: Crossmint.NftMetadata;
    reuploadLinkedFiles: Crossmint.ReuploadLinkedFiles;
}
