/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../../../../index";

/**
 * @example
 *     {
 *         recipient: "polygon:0x1234abcde... or email:<email_address>:polygon",
 *         credential: {
 *             subject: {
 *                 "subjectName": "foo",
 *                 "subjectAge": 20,
 *                 "claim": "bar"
 *             }
 *         }
 *     }
 */
export interface IssueVcRequest {
    /** Recipient address in the format of `<chain>:<address>` or  `email:<email_address>:<chain>`. */
    recipient: string;
    metadata?: Crossmint.IssueVcRequestMetadata;
    credential: Crossmint.IssueVcRequestCredential;
}
