/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../../../../index";

/**
 * @example
 *     {
 *         metadata: {
 *             name: "Verifiable Credential",
 *             description: "The owner of this credential is authorized."
 *         },
 *         credentials: {
 *             type: "degreeForMastersStudent"
 *         }
 *     }
 */
export interface VcCreateTemplateRequest {
    metadata: Crossmint.VcCreateTemplateRequestMetadata;
    /** Credentials parameters */
    credentials: Crossmint.VcCreateTemplateRequestCredentials;
}
