/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         credential: {
 *             "key": "value"
 *         }
 *     }
 *
 * @example
 *     {
 *         credential: {
 *             "key": "value"
 *         }
 *     }
 *
 * @example
 *     {
 *         credential: {
 *             "key": "value"
 *         }
 *     }
 *
 * @example
 *     {
 *         credential: {
 *             "key": "value"
 *         }
 *     }
 */
export interface VerifyCredentialRequest {
    /** The JSON representing a credential. */
    credential: Record<string, unknown>;
}
