/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";
import { TemplateResponse } from "../../../types/TemplateResponse";

export const Response: core.serialization.Schema<
    serializers.nftTemplates.getAllTemplates.Response.Raw,
    Crossmint.TemplateResponse[]
> = core.serialization.list(TemplateResponse);

export declare namespace Response {
    type Raw = TemplateResponse.Raw[];
}
