/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";

export const EditRoyaltyInformationRequestRecipientsItem: core.serialization.ObjectSchema<
    serializers.EditRoyaltyInformationRequestRecipientsItem.Raw,
    Crossmint.EditRoyaltyInformationRequestRecipientsItem
> = core.serialization.object({
    address: core.serialization.string().optional(),
    basisPoints: core.serialization.number().optional(),
});

export declare namespace EditRoyaltyInformationRequestRecipientsItem {
    interface Raw {
        address?: string | null;
        basisPoints?: number | null;
    }
}
