/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";

export const GetBaseUriResponse: core.serialization.ObjectSchema<
    serializers.GetBaseUriResponse.Raw,
    Crossmint.GetBaseUriResponse
> = core.serialization.object({
    uri: core.serialization.string().optional(),
});

export declare namespace GetBaseUriResponse {
    interface Raw {
        uri?: string | null;
    }
}
