/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";

export const GetRoyaltyInformationResponseRecipientsItem: core.serialization.ObjectSchema<
    serializers.GetRoyaltyInformationResponseRecipientsItem.Raw,
    Crossmint.GetRoyaltyInformationResponseRecipientsItem
> = core.serialization.object({
    address: core.serialization.string().optional(),
    basisPoints: core.serialization.number().optional(),
});

export declare namespace GetRoyaltyInformationResponseRecipientsItem {
    interface Raw {
        address?: string | null;
        basisPoints?: number | null;
    }
}
