/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";
import { GetRoyaltyInformationResponseRecipientsItem } from "./GetRoyaltyInformationResponseRecipientsItem";

export const GetRoyaltyInformationResponse: core.serialization.ObjectSchema<
    serializers.GetRoyaltyInformationResponse.Raw,
    Crossmint.GetRoyaltyInformationResponse
> = core.serialization.object({
    recipients: core.serialization.list(GetRoyaltyInformationResponseRecipientsItem).optional(),
});

export declare namespace GetRoyaltyInformationResponse {
    interface Raw {
        recipients?: GetRoyaltyInformationResponseRecipientsItem.Raw[] | null;
    }
}
