/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         page: "page",
 *         perPage: "perPage"
 *     }
 */
export interface FetchContentFromWalletRequest {
    /**
     * Page index
     */
    page: string;
    /**
     * Number of items to display per page
     */
    perPage: string;
}
