/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";

export const CreateTypeRequestCredentialSubjectSchemaItem: core.serialization.ObjectSchema<
    serializers.CreateTypeRequestCredentialSubjectSchemaItem.Raw,
    Crossmint.CreateTypeRequestCredentialSubjectSchemaItem
> = core.serialization.object({
    name: core.serialization.string(),
    type: core.serialization.string(),
});

export declare namespace CreateTypeRequestCredentialSubjectSchemaItem {
    interface Raw {
        name: string;
        type: string;
    }
}
