/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";
import { IssueVcRequestMetadataAttributesItemDisplayType } from "./IssueVcRequestMetadataAttributesItemDisplayType";

export const IssueVcRequestMetadataAttributesItem: core.serialization.ObjectSchema<
    serializers.IssueVcRequestMetadataAttributesItem.Raw,
    Crossmint.IssueVcRequestMetadataAttributesItem
> = core.serialization.object({
    displayType: core.serialization.property(
        "display_type",
        IssueVcRequestMetadataAttributesItemDisplayType.optional()
    ),
    traitType: core.serialization.property("trait_type", core.serialization.string()),
    value: core.serialization.string(),
});

export declare namespace IssueVcRequestMetadataAttributesItem {
    interface Raw {
        display_type?: IssueVcRequestMetadataAttributesItemDisplayType.Raw | null;
        trait_type: string;
        value: string;
    }
}
