/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";
import { IssueVcResponseOnChain } from "./IssueVcResponseOnChain";

export const IssueVcResponse: core.serialization.ObjectSchema<
    serializers.IssueVcResponse.Raw,
    Crossmint.IssueVcResponse
> = core.serialization.object({
    credentialId: core.serialization.string().optional(),
    id: core.serialization.string().optional(),
    onChain: IssueVcResponseOnChain.optional(),
});

export declare namespace IssueVcResponse {
    interface Raw {
        credentialId?: string | null;
        id?: string | null;
        onChain?: IssueVcResponseOnChain.Raw | null;
    }
}
