/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";

export const IssueVcRequestCredential: core.serialization.ObjectSchema<
    serializers.IssueVcRequestCredential.Raw,
    Crossmint.IssueVcRequestCredential
> = core.serialization.object({
    subject: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    expiresAt: core.serialization.string().optional(),
});

export declare namespace IssueVcRequestCredential {
    interface Raw {
        subject: Record<string, unknown>;
        expiresAt?: string | null;
    }
}
