/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";
import { VcCreateTemplateRequestCredentialsDelegatedIssuer } from "./VcCreateTemplateRequestCredentialsDelegatedIssuer";

export const VcCreateTemplateRequestCredentials: core.serialization.ObjectSchema<
    serializers.VcCreateTemplateRequestCredentials.Raw,
    Crossmint.VcCreateTemplateRequestCredentials
> = core.serialization.object({
    type: core.serialization.string(),
    storage: core.serialization.string().optional(),
    delegatedStorageEndpoint: core.serialization.string().optional(),
    encryption: core.serialization.string().optional(),
    delegatedIssuer: VcCreateTemplateRequestCredentialsDelegatedIssuer.optional(),
});

export declare namespace VcCreateTemplateRequestCredentials {
    interface Raw {
        type: string;
        storage?: string | null;
        delegatedStorageEndpoint?: string | null;
        encryption?: string | null;
        delegatedIssuer?: VcCreateTemplateRequestCredentialsDelegatedIssuer.Raw | null;
    }
}
