/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";

export const VcCreateTemplateRequestCredentialsDelegatedIssuer: core.serialization.ObjectSchema<
    serializers.VcCreateTemplateRequestCredentialsDelegatedIssuer.Raw,
    Crossmint.VcCreateTemplateRequestCredentialsDelegatedIssuer
> = core.serialization.object({
    did: core.serialization.string().optional(),
    endpoint: core.serialization.string().optional(),
    token: core.serialization.string().optional(),
});

export declare namespace VcCreateTemplateRequestCredentialsDelegatedIssuer {
    interface Raw {
        did?: string | null;
        endpoint?: string | null;
        token?: string | null;
    }
}
