/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateTypeRequestCredentialSubjectSchemaItem {
    /** The name of credential subject property */
    name: string;
    /** The type of credential subject property */
    type: string;
}
