/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../../../index";

export interface IssueVcResponse {
    /** The credential id */
    credentialId?: string;
    id?: string;
    onChain?: Crossmint.IssueVcResponseOnChain;
}
