/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Display name of your attribute
 */
export type IssueVcRequestMetadataAttributesItemDisplayType = "boost_number" | "boost_percentage" | "number";

export const IssueVcRequestMetadataAttributesItemDisplayType = {
    BoostNumber: "boost_number",
    BoostPercentage: "boost_percentage",
    Number: "number",
} as const;
