/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface IssueVcRequestCredential {
    /** The credential claims object, matching the schema defined on the collection types. */
    subject: Record<string, unknown>;
    /** optional expiration date in ISO 8601 */
    expiresAt?: string;
}
