/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Issuer information, fill only if using delegatedStorage
 */
export interface VcCreateTemplateRequestCredentialsDelegatedIssuer {
    /** The issuer's did */
    did?: string;
    /** The issuer's endpoint to sign credentials */
    endpoint?: string;
    /** Token used for auth on the issuer endpoint */
    token?: string;
}
