/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface VcCreateTemplateRequestMetadata {
    /** The name of your collection (Max length: 32) */
    name: string;
    /** A brief description of credential (Max length: 64) */
    description: string;
}
