/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../../../index";

/**
 * Credentials parameters
 */
export interface VcCreateTemplateRequestCredentials {
    /** The type of credentials inside the collection (blank or 'default' in case no custom type is used) */
    type: string;
    /** Where to store the credential */
    storage?: string;
    /** Only if storage is 'delegated', the endpoint to retrieve the credential from */
    delegatedStorageEndpoint?: string;
    /** Whether to encrypt the credential using the recipient's wallet */
    encryption?: string;
    /** Issuer information, fill only if using delegatedStorage */
    delegatedIssuer?: Crossmint.VcCreateTemplateRequestCredentialsDelegatedIssuer;
}
