/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";
import { Wallet } from "../../../types/Wallet";

export const Response: core.serialization.Schema<serializers.wallet.fetchWallet.Response.Raw, Crossmint.Wallet[]> =
    core.serialization.list(Wallet);

export declare namespace Response {
    type Raw = Wallet.Raw[];
}
