/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";
import { MintingMetadata } from "../../../types/MintingMetadata";
import { Supply } from "../../../types/Supply";

export const EditTemplateRequest: core.serialization.Schema<
    serializers.EditTemplateRequest.Raw,
    Crossmint.EditTemplateRequest
> = core.serialization.undiscriminatedUnion([MintingMetadata, Supply]);

export declare namespace EditTemplateRequest {
    type Raw = MintingMetadata.Raw | Supply.Raw;
}
