/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors/index";
import * as Crossmint from "../index";

export class FailedDependencyError extends errors.CrossmintError {
    constructor(body: Crossmint.FourHundredTwentyFourResponse) {
        super({
            message: "FailedDependencyError",
            statusCode: 424,
            body: body,
        });
        Object.setPrototypeOf(this, FailedDependencyError.prototype);
    }
}
