/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors/index";
import * as Crossmint from "../index";

export class NotImplementedError extends errors.CrossmintError {
    constructor(body: Crossmint.NotImplementedErrorBody) {
        super({
            message: "NotImplementedError",
            statusCode: 501,
            body: body,
        });
        Object.setPrototypeOf(this, NotImplementedError.prototype);
    }
}
