/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Crossmint from "../../../../../api/index";
import * as core from "../../../../../core";
import { UpdateNftCollectionRequestMetadata } from "../../types/UpdateNftCollectionRequestMetadata";

export const UpdateNftCollectionRequest: core.serialization.Schema<
    serializers.UpdateNftCollectionRequest.Raw,
    Crossmint.UpdateNftCollectionRequest
> = core.serialization.object({
    clientId: core.serialization.string(),
    metadata: UpdateNftCollectionRequestMetadata,
});

export declare namespace UpdateNftCollectionRequest {
    interface Raw {
        clientId: string;
        metadata: UpdateNftCollectionRequestMetadata.Raw;
    }
}
