/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";
import { NftObjectEvm } from "../../../types/NftObjectEvm";

export const Response: core.serialization.Schema<
    serializers.nfTs.mintStatusList.Response.Raw,
    Crossmint.NftObjectEvm[]
> = core.serialization.list(NftObjectEvm);

export declare namespace Response {
    type Raw = NftObjectEvm.Raw[];
}
