/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../../../../index";

/**
 * @example
 *     {}
 */
export interface EditRoyaltyInformationRequest {
    /** List of royalty recipients. Note: EVM collections only support a single recipient. Use a contract splitter as recipient in order to send payments to multiple addresses. */
    recipients?: Crossmint.EditRoyaltyInformationRequestRecipientsItem[];
}
