/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         value: true
 *     }
 */
export interface SetTransferabilityRequest {
    /** Toggles the transferability of NFTs within the collection. Set to `false` to disable transfers. */
    value: boolean;
}
