/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";
import { Email } from "./Email";
import { UserId } from "./UserId";

export const CreateWalletRequest: core.serialization.Schema<
    serializers.CreateWalletRequest.Raw,
    Crossmint.CreateWalletRequest
> = core.serialization.undiscriminatedUnion([Email, UserId]);

export declare namespace CreateWalletRequest {
    type Raw = Email.Raw | UserId.Raw;
}
