/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Crossmint from "../../../../../api/index";
import * as core from "../../../../../core";

export const SignMessageRequest: core.serialization.Schema<
    serializers.SignMessageRequest.Raw,
    Crossmint.SignMessageRequest
> = core.serialization.object({
    message: core.serialization.string(),
});

export declare namespace SignMessageRequest {
    interface Raw {
        message: string;
    }
}
