/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../index";
import * as Crossmint from "../../../api/index";
import * as core from "../../../core";
import { AllChains } from "../../types/AllChains";

export const TransferRequest: core.serialization.Schema<serializers.TransferRequest.Raw, Crossmint.TransferRequest> =
    core.serialization.object({
        chain: AllChains.optional(),
        tokenId: core.serialization.string().optional(),
        fromAddress: core.serialization.string().optional(),
        toAddress: core.serialization.string().optional(),
        tokenMintAddress: core.serialization.string().optional(),
    });

export declare namespace TransferRequest {
    interface Raw {
        chain?: AllChains.Raw | null;
        tokenId?: string | null;
        fromAddress?: string | null;
        toAddress?: string | null;
        tokenMintAddress?: string | null;
    }
}
