/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Crossmint from "../../../../../api/index";
import * as core from "../../../../../core";
import { CreateTypeIdempotentRequestCredentialSubjectSchemaItem } from "../../types/CreateTypeIdempotentRequestCredentialSubjectSchemaItem";
import { CreateTypeIdempotentRequestNestedTypeSchemaItem } from "../../types/CreateTypeIdempotentRequestNestedTypeSchemaItem";

export const CreateTypeIdempotentRequest: core.serialization.Schema<
    serializers.CreateTypeIdempotentRequest.Raw,
    Crossmint.CreateTypeIdempotentRequest
> = core.serialization.object({
    credentialSubjectSchema: core.serialization.list(CreateTypeIdempotentRequestCredentialSubjectSchemaItem),
    nestedTypeSchema: core.serialization.list(CreateTypeIdempotentRequestNestedTypeSchemaItem).optional(),
});

export declare namespace CreateTypeIdempotentRequest {
    interface Raw {
        credentialSubjectSchema: CreateTypeIdempotentRequestCredentialSubjectSchemaItem.Raw[];
        nestedTypeSchema?: CreateTypeIdempotentRequestNestedTypeSchemaItem.Raw[] | null;
    }
}
