/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Crossmint from "../../../../../api/index";
import * as core from "../../../../../core";
import { IssueVcRequestMetadata } from "../../types/IssueVcRequestMetadata";
import { IssueVcRequestCredential } from "../../types/IssueVcRequestCredential";

export const IssueVcRequest: core.serialization.Schema<serializers.IssueVcRequest.Raw, Crossmint.IssueVcRequest> =
    core.serialization.object({
        recipient: core.serialization.string(),
        metadata: IssueVcRequestMetadata.optional(),
        credential: IssueVcRequestCredential,
    });

export declare namespace IssueVcRequest {
    interface Raw {
        recipient: string;
        metadata?: IssueVcRequestMetadata.Raw | null;
        credential: IssueVcRequestCredential.Raw;
    }
}
