/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../../../index";

export interface EvmTransfer {
    chain?: Crossmint.EvmChains;
    /** The wallet address for the current owner */
    from?: string;
    /** The wallet address the token should be transferred to */
    to?: string;
    /** The contract address of the token to transfer */
    contractAddress?: string;
    /** The numeric tokenId of the token to be transferred */
    tokenId?: string;
    /** Required for ERC-1155 only, not relevant for ERC-721 tokens */
    quantity?: string;
}
