/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface BatchError {
    error?: boolean;
    message?: string;
    /** A list of specific validation errors. */
    validationErrors?: Crossmint.ValidationError[];
}
