/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface BurnNftResponse {
    /** Can be used to check the status via the [action status API](/api-reference/common/get-action-status) */
    actionId?: string;
    /** The action performed, in this case `nfts.delete` */
    action?: string;
    /** Current status of the async operation. One of `pending` or `succeeded` */
    status?: string;
    data?: Crossmint.BurnNftResponseData;
    /** The time this operation was initiated in UTC. */
    startedAt?: Date;
    /**
     * The time this operation completed in UTC.
     *
     * This is only present when `status` is `succeeded`
     */
    completedAt?: Date;
    /** The URL path to obtain current status with [action status api](/api-reference/common/get-action-status) */
    resource?: string;
}
