/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BurnNftResponseDataToken {
    /** The Crossmint identifier for the NFT. This will be a UUID. */
    id?: string;
    /** The numeric tokenId of the NFT in the contract. */
    tokenId?: string;
}
