/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface BurnNftResponseData {
    /** Refer to the [supported chains](/introduction/supported-chains) page for more info */
    chain?: string;
    /**
     * The onchain transaction ID related to the request.
     *
     * This is only present when `status` is `succeeded`
     */
    txId?: string;
    collection?: Crossmint.BurnNftResponseDataCollection;
    token?: Crossmint.BurnNftResponseDataToken;
}
