/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CheckoutMintSuccess {
    /** A URL to send the user to in order to capture payment and start the minting process */
    checkoutUrl?: string;
}
