/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Information about your collection, to be displayed on the checkout page.
 */
export interface Collection {
    /** The title of your collection */
    title?: string;
    /** A description for your collection */
    description?: string;
    /** Full URL to an image for your collection. */
    photo?: string;
}
