/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Blockchain you would like to use for this collection
 */
export type CreateCollectionBodyChain =
    | "aptos"
    | "arbitrum"
    | "arbitrum-sepolia"
    | "astar-zkevm"
    | "base"
    | "base-sepolia"
    | "bsc"
    | "ethereum"
    | "ethereum-sepolia"
    | "optimism"
    | "optimism-sepolia"
    | "polygon"
    | "polygon-amoy"
    | "skale-nebula"
    | "skale-nebula-testnet"
    | "solana"
    | "zkyoto"
    | "zora"
    | "zora-sepolia";

export const CreateCollectionBodyChain = {
    Aptos: "aptos",
    Arbitrum: "arbitrum",
    ArbitrumSepolia: "arbitrum-sepolia",
    AstarZkevm: "astar-zkevm",
    Base: "base",
    BaseSepolia: "base-sepolia",
    Bsc: "bsc",
    Ethereum: "ethereum",
    EthereumSepolia: "ethereum-sepolia",
    Optimism: "optimism",
    OptimismSepolia: "optimism-sepolia",
    Polygon: "polygon",
    PolygonAmoy: "polygon-amoy",
    SkaleNebula: "skale-nebula",
    SkaleNebulaTestnet: "skale-nebula-testnet",
    Solana: "solana",
    Zkyoto: "zkyoto",
    Zora: "zora",
    ZoraSepolia: "zora-sepolia",
} as const;
