/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether or not this collection is fungible. Only EVM collections may be set as semi-fungible
 */
export type CreateCollectionBodyFungibility = "non-fungible" | "semi-fungible";

export const CreateCollectionBodyFungibility = {
    NonFungible: "non-fungible",
    SemiFungible: "semi-fungible",
} as const;
