/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateCollectionBodyMetadata {
    /** Collection name (Max length: 32) */
    name: string;
    /** URL pointing to an image that represents the collection */
    imageUrl?: string;
    /** A description of the NFT collection */
    description: string;
    /** **EVM only** NFT collection symbol */
    symbol?: string;
}
