/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Supply details
 */
export interface CreateTemplateBodySupply {
    /** Supply limit, Set to 1 for ERC721. */
    limit?: number;
}
