/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface CreateCollectionResponse {
    id?: string;
    metadata?: Crossmint.CreateCollectionResponseMetadata;
    fungibility?: string;
    onChain?: Crossmint.CreateCollectionResponseOnChain;
    actionId?: string;
}
