/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface CreateOrderResponse {
    /** A token exclusively scoped to a particular order, allowing for the reading or updating of that order. */
    clientSecret?: string;
    order?: Crossmint.OrderObject;
}
