/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * On-chain details
 */
export interface CreateTemplateBodyOnChain {
    /** The token ID. Only relevant for SFT (ERC-1155) collections. Leave empty for NFT/ERC-721 collections. */
    tokenId?: string;
}
