/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface EditNftResponseDataToken {
    id?: string;
    owner?: Crossmint.EditNftResponseDataTokenOwner;
    tokenId?: string;
}
