/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EvmChains =
    | "arbitrum"
    | "arbitrumnova"
    | "arbitrum-sepolia"
    | "base"
    | "base-sepolia"
    | "bsc"
    | "ethereum"
    | "ethereum-sepolia"
    | "optimism"
    | "optimism-sepolia"
    | "polygon"
    | "polygon-amoy"
    | "zkyoto"
    | "zora"
    | "zora-sepolia";

export const EvmChains = {
    Arbitrum: "arbitrum",
    Arbitrumnova: "arbitrumnova",
    ArbitrumSepolia: "arbitrum-sepolia",
    Base: "base",
    BaseSepolia: "base-sepolia",
    Bsc: "bsc",
    Ethereum: "ethereum",
    EthereumSepolia: "ethereum-sepolia",
    Optimism: "optimism",
    OptimismSepolia: "optimism-sepolia",
    Polygon: "polygon",
    PolygonAmoy: "polygon-amoy",
    Zkyoto: "zkyoto",
    Zora: "zora",
    ZoraSepolia: "zora-sepolia",
} as const;
