/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EvmPaymentMethods =
    | "arbitrum-sepolia"
    | "base-sepolia"
    | "ethereum-sepolia"
    | "optimism-sepolia"
    | "arbitrum"
    | "bsc"
    | "ethereum"
    | "optimism";

export const EvmPaymentMethods = {
    ArbitrumSepolia: "arbitrum-sepolia",
    BaseSepolia: "base-sepolia",
    EthereumSepolia: "ethereum-sepolia",
    OptimismSepolia: "optimism-sepolia",
    Arbitrum: "arbitrum",
    Bsc: "bsc",
    Ethereum: "ethereum",
    Optimism: "optimism",
} as const;
