/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface EvmPayment {
    /** Email that the receipt will be sent to. */
    receiptEmail?: string;
    method: Crossmint.EvmPaymentMethods;
    currency: Crossmint.EvmPaymentCurrency;
    /** An EVM wallet address. */
    payerAddress?: string;
}
