/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type FiatPaymentCurrency = "usd" | "eur" | "aud" | "gbp" | "jpy" | "sgd" | "hkd" | "krw" | "inr" | "vnd";

export const FiatPaymentCurrency = {
    Usd: "usd",
    Eur: "eur",
    Aud: "aud",
    Gbp: "gbp",
    Jpy: "jpy",
    Sgd: "sgd",
    Hkd: "hkd",
    Krw: "krw",
    Inr: "inr",
    Vnd: "vnd",
} as const;
