/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface Fiat {
    /** Email that the receipt will be sent to. */
    receiptEmail?: string;
    method: "stripe-payment-element";
    currency?: Crossmint.PaymentCurrencyCurrency;
}
