/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetCollectionResponseMetadata {
    name?: string;
    description?: string;
    imageUrl?: string;
    symbol?: string;
}
