/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface GetCollectionResponse {
    id?: string;
    metadata?: Crossmint.GetCollectionResponseMetadata;
    fungibility?: string;
    onChain?: Crossmint.GetCollectionResponseOnChain;
    supplyLimit?: number;
    payments?: Crossmint.GetCollectionResponsePayments;
}
