/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface LineItemsItem {
    /** The collection locator of the line item. Eg. 'crossmint:<projectId>:<collectionId>', 'crossmint:<collectionId>'. These fields can be retrieved from the Crossmint console. */
    collectionLocator: string;
    /** Information that you pass to your contract mint function. */
    callData?: Crossmint.LineItemsItemCallData;
}
