/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Information that you pass to your contract mint function.
 */
export interface LineItemsCallDataCallData {
    /** The total price of the line item. It must be the same as the contract expects to receive. Read https://docs.crossmint.com/nft-checkout/advanced/component-properties#mintconfig */
    totalPrice?: string;
}
