/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Locale for the checkout, in IETF BCP 47. It impacts the email receipt language. Ensure your UI is set to the same language as specified here. Throws an error if passed an invalid language.
 */
export type Locale =
    | "en-US"
    | "es-ES"
    | "fr-FR"
    | "it-IT"
    | "ko-KR"
    | "pt-PT"
    | "ja-JP"
    | "zh-CN"
    | "zh-TW"
    | "de-DE"
    | "ru-RU"
    | "tr-TR"
    | "uk-UA"
    | "th-TH"
    | "vi-VN"
    | "Klingon";

export const Locale = {
    EnUs: "en-US",
    EsEs: "es-ES",
    FrFr: "fr-FR",
    ItIt: "it-IT",
    KoKr: "ko-KR",
    PtPt: "pt-PT",
    JaJp: "ja-JP",
    ZhCn: "zh-CN",
    ZhTw: "zh-TW",
    DeDe: "de-DE",
    RuRu: "ru-RU",
    TrTr: "tr-TR",
    UkUa: "uk-UA",
    ThTh: "th-TH",
    ViVn: "vi-VN",
    Klingon: "Klingon",
} as const;
