/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface MintStatus {
    /** The latest status of the mint */
    status?: Crossmint.MintStatusStatus;
    /** The address of the mint */
    mintAddress?: string;
    /** The wallet address the NFT is minted to */
    walletAddress?: string;
    /** The arguments you sent via the `whPassThroughArgs` from `/checkout/mint` */
    passThroughArgs?: string;
}
