/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface MintResponseSolana200 {
    id?: string;
    onChain?: Crossmint.MintResponseSolana200OnChain;
    actionId?: string;
}
