/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface MintResponseSolana200Subsequent extends Crossmint.NftObjectSolana {
    /** actionId for the request */
    actionId?: string;
}
