/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface MintStatusSolana200 extends Crossmint.NftObjectSolana {
    /** URL to API endpoint for requesting status */
    action?: string;
}
