/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface MintResponseEvm200 {
    id?: string;
    onChain?: Crossmint.MintResponseEvm200OnChain;
    actionId?: string;
}
