/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Arguments sent to your smart contract
 */
export interface MintConfig {
    totalPrice?: string;
    /** Any custom arguments to your minting function should be configured here. */
    ""?: Record<string, unknown>;
}
