/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The latest status of the mint
 */
export type MintStatusStatus = "minting" | "success" | "error";

export const MintStatusStatus = {
    Minting: "minting",
    Success: "success",
    Error: "error",
} as const;
