/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface Nft {
    name?: string;
    symbol?: string;
    description?: string;
    /** A url that represents the image for the NFT */
    image?: string;
    collection?: Crossmint.NftCollection;
    attributes?: Crossmint.NftAttributesItem[];
    properties?: Crossmint.NftProperties;
    mintHash?: string;
    sellerFeeBasisPoints?: number;
}
