/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface NftcarItemMetadata {
    assetId?: string;
    name?: string;
    description?: string;
    image?: string;
    attributes?: Crossmint.NftcarItemMetadataAttributesItem[];
}
