/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface NftevmItemMetadata {
    attributes?: Crossmint.NftevmItemMetadataAttributesItem[];
    collection?: Record<string, unknown>;
    description?: string;
    /** URL that represents the image for the NFT */
    image?: string;
    /** Optional URL representing a video or other multimedia file */
    animationUrl?: string;
    name?: string;
}
