/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface NftMetadataAttributesItem {
    /** Display name of your attribute */
    displayType?: Crossmint.NftMetadataAttributesItemDisplayType;
    /** The name of the trait */
    traitType: string;
    /** The value of the trait */
    value: string;
}
