/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

/**
 * Optional if [baseURI](/api-reference/minting/collection/set-base-uri) is set.
 */
export type NftMetadataOptions =
    | Crossmint.NftMetadata
    /**
     * Enter a URL to a JSON file containing the metadata contents */
    | string
    | Crossmint.NftMetadataSolana
    /**
     * Enter a URL to a JSON file containing the metadata contents */
    | Crossmint.NftMetadataOptionsName;
