/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface NftObjectSolanaOnChain {
    status?: string;
    mintHash?: string;
    txId?: string;
    owner?: string;
    chain?: string;
}
