/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface NftObjectEvm {
    id?: string;
    metadata?: Crossmint.NftObjectEvmMetadata;
    onChain?: Crossmint.NftObjectEvmOnChain;
}
