/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface NftObjectEvmOnChain {
    status?: string;
    tokenId?: string;
    owner?: string;
    txId?: string;
    contractAddress?: string;
    chain?: string;
}
