/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface NftsolItemMetadataAttributesItem {
    value?: Crossmint.NftsolItemMetadataAttributesItemValue;
    traitType?: string;
}
