/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface NftsolItem {
    /** The blockchain used in the request, `solana` in this case. */
    chain?: string;
    /** The unique identifier of this NFT on Solana */
    mintHash?: string;
    metadata?: Crossmint.NftsolItemMetadata;
    /** The address of the NFT on the blockchain */
    locator?: string;
}
