/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface NftsolItemMetadata {
    name?: string;
    description?: string;
    /** A URL that represents the image for the NFT */
    image?: string;
    attributes?: Crossmint.NftsolItemMetadataAttributesItem[];
}
