/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface OrderObjectLineItemsItemDeliveryRecipient {
    locator?: string;
    email?: string;
    walletAddress?: string;
}
