/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface OrderObjectLineItemsItemQuote {
    status?: string;
    charges?: Crossmint.OrderObjectLineItemsItemQuoteCharges;
    totalPrice?: Crossmint.OrderObjectLineItemsItemQuoteTotalPrice;
}
