/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface OrderObjectLineItemsItem {
    chain?: string;
    quantity?: number;
    callData?: Crossmint.OrderObjectLineItemsItemCallData;
    metadata?: Crossmint.OrderObjectLineItemsItemMetadata;
    quote?: Crossmint.OrderObjectLineItemsItemQuote;
    delivery?: Crossmint.OrderObjectLineItemsItemDelivery;
}
