/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface OrderObjectPayment {
    status?: string;
    method?: string;
    currency?: string;
    preparation?: Crossmint.OrderObjectPaymentPreparation;
}
