/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Enable payments for this collection by setting `price`, `recipientAddress` and `currency`
 */
export interface PaymentsObject {
    /** The price of the token in native currency for the selected chain */
    price?: string;
    /** The wallet address to receive payouts */
    recipientAddress?: string;
    /** The currency for the price of the NFT. Defaults to the native currency of the chain */
    currency?: string;
}
