/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export type Payment = Crossmint.EvmPaymentMethods | Crossmint.SolanaPaymentMethods | Crossmint.FiatPaymentMethods;
