/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PaymentZeroCurrency = "eth" | "usdc" | "degen" | "brett" | "toshi";

export const PaymentZeroCurrency = {
    Eth: "eth",
    Usdc: "usdc",
    Degen: "degen",
    Brett: "brett",
    Toshi: "toshi",
} as const;
