/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Recipient of the items being purchased. Crossmint will create a custodial wallet address for the user on the fly, that they can later log in to. If no recipient is passed, an order will be created with the status 'requires-recipient', until you pass one.
 */
export interface RecipientEmail {
    email: string;
}
