/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Allowed formats:
 *
 * `<chain>:<address>` or
 *
 * `email:<email_address>:<chain>` or
 *
 * `userId:<userId>:<chain>`
 *
 * [see here for more info](/minting/advanced/specify-recipient)
 */
export type Recipient = string;
