/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The URLs to redirect the user to upon comletion or cancellation of the checkout page.
 */
export interface Redirect {
    /** The URL to redirect the customer to when the customer's payment information is accepted. */
    continue?: string;
    /** The URL to redirect the customer cancels the payment. */
    cancel?: string;
}
