/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Any URLs in the metadata object will be resolved and reuploaded to IPFS [Default: true]
 */
export type ReuploadLinkedFiles = boolean;
