/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Solana {
    chain?: "solana";
    /** The wallet address for the current owner */
    from?: string;
    /** The wallet address the token should be transferred to */
    to?: string;
    /** The mintHash of the token to transfer */
    tokenMintAddress?: string;
}
