/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SolanaPaymentCurrency = "sol" | "usdc" | "bonk" | "wif" | "mother";

export const SolanaPaymentCurrency = {
    Sol: "sol",
    Usdc: "usdc",
    Bonk: "bonk",
    Wif: "wif",
    Mother: "mother",
} as const;
