/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface SolanaPayment {
    /** Email that the receipt will be sent to. */
    receiptEmail?: string;
    method: "solana";
    currency: Crossmint.SolanaPaymentCurrency;
    /** A Solana public key. */
    payerAddress?: string;
}
