/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface TemplateResponse {
    templateId?: string;
    metadata?: Crossmint.TemplateResponseMetadata;
    onChain?: Crossmint.TemplateResponseOnChain;
    supply?: Crossmint.TemplateResponseSupply;
}
