/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TransferPendingVerification {
    /** A URL to send the user to in order to perform a persona verification. If the user has failed the OTP challenge 3 times, this will be the only option. */
    personaUrl?: string;
}
