/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface UpdateCollectionResponse {
    actionId?: string;
    action?: string;
    status?: string;
    data?: Crossmint.UpdateCollectionResponseData;
    startedAt?: Date;
    resource?: string;
}
