/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The usage data for the specified dimension.
 */
export interface UsageResponseDataUsage {
    /** YYYY-MM format indicating the month */
    month?: string;
    /** The number of active wallets for the given month */
    activeWallets?: number;
}
