/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../index";

export interface UsageResponseData {
    /** The type of usage data returned. */
    dimension?: string;
    /** The usage data for the specified dimension. */
    usage?: Crossmint.UsageResponseDataUsage;
}
