/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface VerificationRequestSent {
    /** A message indicating the result. */
    message?: string;
    /** An ID that can be used to poll the [actions API](/api-reference/common/get-action-status). */
    actionId?: string;
}
