/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Wallet {
    /** The blockchain the wallet is on */
    chain?: string;
    /** The public address of the wallet */
    publicKey?: string;
}
