/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WalletsTransfer {
    chain: string;
    /** The NFT token ID */
    tokenId?: string;
    /** The wallet address for the current owner */
    fromAddress: string;
    /** The wallet address to send the NFT to */
    toAddress: string;
    /** The NFT token mint address */
    tokenMintAddress: string;
}
