/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../../../../index";

/**
 * @example
 *     {
 *         payment: {
 *             method: Crossmint.PaymentZeroMethod.ArbitrumSepolia,
 *             currency: Crossmint.PaymentZeroCurrency.Eth
 *         },
 *         lineItems: {
 *             collectionLocator: "crossmint:<collectionId>"
 *         }
 *     }
 */
export interface CheckoutCreateOrderRequest {
    recipient?: Crossmint.Recipient;
    locale?: Crossmint.Locale;
    payment: Crossmint.Payment;
    lineItems: Crossmint.LineItems;
}
