/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../../../../index";

/**
 * @example
 *     {
 *         clientId: "clientId",
 *         userId: "userId"
 *     }
 */
export interface CheckoutMintRequest {
    /** The clientId of a previously created collection */
    clientId: string;
    /** The userId of a previously created wallet */
    userId: string;
    /** Target email */
    emailTo?: string;
    /** Crypto address to mint the NFT to */
    mintTo?: string;
    /** Payment method */
    paymentMethod?: string;
    listingId?: string;
    collection?: Crossmint.CheckoutMintRequestCollection;
    redirect?: Crossmint.CheckoutMintRequestRedirect;
    mintConfig?: Crossmint.CheckoutMintRequestMintConfig;
    /** Any arguments to included in the webhook status updates */
    whPassThroughArgs?: string;
}
