/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Crossmint from "../../../../../api/index";
import * as core from "../../../../../core";
import { NftMetadata } from "../../../../types/NftMetadata";
import { ReuploadLinkedFiles } from "../../../../types/ReuploadLinkedFiles";

export const EditNftByLocatorRequest: core.serialization.Schema<
    serializers.EditNftByLocatorRequest.Raw,
    Crossmint.EditNftByLocatorRequest
> = core.serialization.object({
    metadata: NftMetadata,
    reuploadLinkedFiles: ReuploadLinkedFiles,
});

export declare namespace EditNftByLocatorRequest {
    interface Raw {
        metadata: NftMetadata.Raw;
        reuploadLinkedFiles: ReuploadLinkedFiles.Raw;
    }
}
