/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Crossmint from "../../../../../api/index";
import * as core from "../../../../../core";
import { NftMetadataOptions } from "../../../../types/NftMetadataOptions";
import { ReuploadLinkedFiles } from "../../../../types/ReuploadLinkedFiles";

export const EditNftRequest: core.serialization.Schema<serializers.EditNftRequest.Raw, Crossmint.EditNftRequest> =
    core.serialization.object({
        metadata: NftMetadataOptions,
        reuploadLinkedFiles: ReuploadLinkedFiles.optional(),
    });

export declare namespace EditNftRequest {
    interface Raw {
        metadata: NftMetadataOptions.Raw;
        reuploadLinkedFiles?: ReuploadLinkedFiles.Raw | null;
    }
}
