/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Crossmint from "../../../../../api/index";
import * as core from "../../../../../core";
import { Recipient } from "../../../../types/Recipient";

export const MintSftRequest: core.serialization.Schema<
    serializers.MintSftRequest.Raw,
    Omit<Crossmint.MintSftRequest, "idempotencyKey">
> = core.serialization.object({
    templateId: core.serialization.string(),
    recipient: Recipient,
    amount: core.serialization.number().optional(),
});

export declare namespace MintSftRequest {
    interface Raw {
        templateId: string;
        recipient: Recipient.Raw;
        amount?: number | null;
    }
}
