/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Crossmint from "../../../../../api/index";
import * as core from "../../../../../core";
import { Recipient } from "../../../../types/Recipient";
import { NftMetadataOptions } from "../../../../types/NftMetadataOptions";
import { ReuploadLinkedFiles } from "../../../../types/ReuploadLinkedFiles";
import { Compressed } from "../../../../types/Compressed";

export const MintNftIdempotentRequest: core.serialization.Schema<
    serializers.MintNftIdempotentRequest.Raw,
    Crossmint.MintNftIdempotentRequest
> = core.serialization.object({
    recipient: Recipient,
    metadata: NftMetadataOptions,
    reuploadLinkedFiles: ReuploadLinkedFiles.optional(),
    compressed: Compressed.optional(),
});

export declare namespace MintNftIdempotentRequest {
    interface Raw {
        recipient: Recipient.Raw;
        metadata: NftMetadataOptions.Raw;
        reuploadLinkedFiles?: ReuploadLinkedFiles.Raw | null;
        compressed?: Compressed.Raw | null;
    }
}
