/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../../index";

/**
 * @example
 *     {}
 */
export interface NftRequest {
    chain?: Crossmint.AllChains;
    /** The numeric token ID of the NFT to be transferred, only used for EVM tokens */
    tokenId?: string;
    /** The wallet address for the current owner */
    fromAddress?: string;
    /** The wallet address to send the NFT to */
    toAddress?: string;
    /**
     * **Solana**: mintHash
     *
     * **EVM**: token contract address
     *
     */
    tokenMintAddress?: string;
}
