/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../../../../index";

/**
 * @example
 *     {
 *         clientId: "clientId",
 *         metadata: {
 *             title: "title",
 *             imageUrl: "imageUrl"
 *         }
 *     }
 */
export interface UpdateNftCollectionRequest {
    clientId: string;
    metadata: Crossmint.UpdateNftCollectionRequestMetadata;
}
