/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../../../../index";

/**
 * @example
 *     {}
 */
export interface OrderDto {
    recipient?: Crossmint.Recipient;
    locale?: Crossmint.Locale;
    payment?: Crossmint.Payment;
}
