/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../../../index";

export type EditTemplateRequest = Crossmint.MintingMetadata | Crossmint.Supply;
