/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../../../../index";

/**
 * @example
 *     {
 *         nativePrice: "nativePrice",
 *         quoteCurrency: Crossmint.QuoteRequestQuoteCurrency.Usd
 *     }
 */
export interface QuoteRequest {
    /**
     * Price in specified chain currency to quote.
     * The chain is derived from the chain your collection is on.
     * If your chain is on the Solana network, the parameter would be the SOL amount, not Lamports.
     */
    nativePrice: string;
    /**
     * Price in specified currency to quote
     */
    quoteCurrency: Crossmint.QuoteRequestQuoteCurrency;
}
