/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";

export const RegisterNftCollectionRequestArgsCandyMachineId: core.serialization.ObjectSchema<
    serializers.RegisterNftCollectionRequestArgsCandyMachineId.Raw,
    Crossmint.RegisterNftCollectionRequestArgsCandyMachineId
> = core.serialization.object({
    candyMachineId: core.serialization.string(),
});

export declare namespace RegisterNftCollectionRequestArgsCandyMachineId {
    interface Raw {
        candyMachineId: string;
    }
}
