/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";

export const RegisterNftCollectionRequestCategory: core.serialization.Schema<
    serializers.RegisterNftCollectionRequestCategory.Raw,
    Crossmint.RegisterNftCollectionRequestCategory
> = core.serialization.enum_(["loyalty", "art", "music", "gaming", "ticketing", "charity", "other"]);

export declare namespace RegisterNftCollectionRequestCategory {
    type Raw = "loyalty" | "art" | "music" | "gaming" | "ticketing" | "charity" | "other";
}
