/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";

export const RegisterNftCollectionRequestOwnership: core.serialization.Schema<
    serializers.RegisterNftCollectionRequestOwnership.Raw,
    Crossmint.RegisterNftCollectionRequestOwnership
> = core.serialization.enum_(["external", "self"]);

export declare namespace RegisterNftCollectionRequestOwnership {
    type Raw = "external" | "self";
}
