/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";
import { RegisterNftCollectionRequestMetadataSocial } from "./RegisterNftCollectionRequestMetadataSocial";

export const RegisterNftCollectionRequestMetadata: core.serialization.ObjectSchema<
    serializers.RegisterNftCollectionRequestMetadata.Raw,
    Crossmint.RegisterNftCollectionRequestMetadata
> = core.serialization.object({
    title: core.serialization.string(),
    description: core.serialization.string(),
    imageUrl: core.serialization.string(),
    social: RegisterNftCollectionRequestMetadataSocial.optional(),
});

export declare namespace RegisterNftCollectionRequestMetadata {
    interface Raw {
        title: string;
        description: string;
        imageUrl: string;
        social?: RegisterNftCollectionRequestMetadataSocial.Raw | null;
    }
}
