/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";

export const RegisterNftCollectionRequestScopesItem: core.serialization.Schema<
    serializers.RegisterNftCollectionRequestScopesItem.Raw,
    Crossmint.RegisterNftCollectionRequestScopesItem
> = core.serialization.enum_(["payments:credit-card", "payments:cross-chain"]);

export declare namespace RegisterNftCollectionRequestScopesItem {
    type Raw = "payments:credit-card" | "payments:cross-chain";
}
