/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";
import { RegisterNftCollectionRequestArgsCandyMachineId } from "./RegisterNftCollectionRequestArgsCandyMachineId";
import { Evm } from "./Evm";

export const RegisterNftCollectionRequestArgs: core.serialization.Schema<
    serializers.RegisterNftCollectionRequestArgs.Raw,
    Crossmint.RegisterNftCollectionRequestArgs
> = core.serialization.undiscriminatedUnion([RegisterNftCollectionRequestArgsCandyMachineId, Evm]);

export declare namespace RegisterNftCollectionRequestArgs {
    type Raw = RegisterNftCollectionRequestArgsCandyMachineId.Raw | Evm.Raw;
}
