/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";
import { UpdateNftCollectionRequestMetadataSocial } from "./UpdateNftCollectionRequestMetadataSocial";

export const UpdateNftCollectionRequestMetadata: core.serialization.ObjectSchema<
    serializers.UpdateNftCollectionRequestMetadata.Raw,
    Crossmint.UpdateNftCollectionRequestMetadata
> = core.serialization.object({
    title: core.serialization.string(),
    imageUrl: core.serialization.string(),
    social: UpdateNftCollectionRequestMetadataSocial.optional(),
});

export declare namespace UpdateNftCollectionRequestMetadata {
    interface Raw {
        title: string;
        imageUrl: string;
        social?: UpdateNftCollectionRequestMetadataSocial.Raw | null;
    }
}
