/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { OutdatedContract } from "./OutdatedContract";
import { OldCollection } from "./OldCollection";
import { SolanaNotSupported } from "./SolanaNotSupported";
import { ExternalCollection } from "./ExternalCollection";
import { SftCollection } from "./SftCollection";

export const BadRequestErrorBody: core.serialization.Schema<
    serializers.BadRequestErrorBody.Raw,
    Crossmint.BadRequestErrorBody
> = core.serialization.undiscriminatedUnion([
    OutdatedContract,
    OldCollection,
    SolanaNotSupported,
    ExternalCollection,
    SftCollection,
]);

export declare namespace BadRequestErrorBody {
    type Raw =
        | OutdatedContract.Raw
        | OldCollection.Raw
        | SolanaNotSupported.Raw
        | ExternalCollection.Raw
        | SftCollection.Raw;
}
