/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { MintResponseEvm200 } from "./MintResponseEvm200";

export const BatchMintResponse: core.serialization.ObjectSchema<
    serializers.BatchMintResponse.Raw,
    Crossmint.BatchMintResponse
> = core.serialization.object({
    results: core.serialization.list(MintResponseEvm200),
});

export declare namespace BatchMintResponse {
    interface Raw {
        results: MintResponseEvm200.Raw[];
    }
}
