/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const BurnNftResponseDataToken: core.serialization.ObjectSchema<
    serializers.BurnNftResponseDataToken.Raw,
    Crossmint.BurnNftResponseDataToken
> = core.serialization.object({
    id: core.serialization.string().optional(),
    tokenId: core.serialization.string().optional(),
});

export declare namespace BurnNftResponseDataToken {
    interface Raw {
        id?: string | null;
        tokenId?: string | null;
    }
}
