/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { BurnNftResponseDataCollection } from "./BurnNftResponseDataCollection";
import { BurnNftResponseDataToken } from "./BurnNftResponseDataToken";

export const BurnNftResponseData: core.serialization.ObjectSchema<
    serializers.BurnNftResponseData.Raw,
    Crossmint.BurnNftResponseData
> = core.serialization.object({
    chain: core.serialization.string().optional(),
    txId: core.serialization.string().optional(),
    collection: BurnNftResponseDataCollection.optional(),
    token: BurnNftResponseDataToken.optional(),
});

export declare namespace BurnNftResponseData {
    interface Raw {
        chain?: string | null;
        txId?: string | null;
        collection?: BurnNftResponseDataCollection.Raw | null;
        token?: BurnNftResponseDataToken.Raw | null;
    }
}
