/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { NftcarItem } from "./NftcarItem";

export const Cardano: core.serialization.Schema<serializers.Cardano.Raw, Crossmint.Cardano> =
    core.serialization.list(NftcarItem);

export declare namespace Cardano {
    type Raw = NftcarItem.Raw[];
}
