/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { Collection } from "./Collection";
import { Redirect } from "./Redirect";
import { MintConfig } from "./MintConfig";

export const Checkout: core.serialization.ObjectSchema<serializers.Checkout.Raw, Crossmint.Checkout> =
    core.serialization.object({
        clientId: core.serialization.string(),
        collection: Collection.optional(),
        redirect: Redirect.optional(),
        mintConfig: MintConfig.optional(),
        emailTo: core.serialization.string().optional(),
        mintTo: core.serialization.string().optional(),
        paymentMethod: core.serialization.string().optional(),
        whPassThroughArgs: core.serialization
            .record(core.serialization.string(), core.serialization.unknown())
            .optional(),
        listingId: core.serialization.string().optional(),
    });

export declare namespace Checkout {
    interface Raw {
        clientId: string;
        collection?: Collection.Raw | null;
        redirect?: Redirect.Raw | null;
        mintConfig?: MintConfig.Raw | null;
        emailTo?: string | null;
        mintTo?: string | null;
        paymentMethod?: string | null;
        whPassThroughArgs?: Record<string, unknown> | null;
        listingId?: string | null;
    }
}
