/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const Collection: core.serialization.ObjectSchema<serializers.Collection.Raw, Crossmint.Collection> =
    core.serialization.object({
        title: core.serialization.string().optional(),
        description: core.serialization.string().optional(),
        photo: core.serialization.string().optional(),
    });

export declare namespace Collection {
    interface Raw {
        title?: string | null;
        description?: string | null;
        photo?: string | null;
    }
}
