/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const Compressed: core.serialization.Schema<serializers.Compressed.Raw, Crossmint.Compressed> =
    core.serialization.boolean();

export declare namespace Compressed {
    type Raw = boolean;
}
