/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { OrderObject } from "./OrderObject";

export const CreateOrderResponse: core.serialization.ObjectSchema<
    serializers.CreateOrderResponse.Raw,
    Crossmint.CreateOrderResponse
> = core.serialization.object({
    clientSecret: core.serialization.string().optional(),
    order: OrderObject.optional(),
});

export declare namespace CreateOrderResponse {
    interface Raw {
        clientSecret?: string | null;
        order?: OrderObject.Raw | null;
    }
}
