/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const CreateCollectionResponseOnChain: core.serialization.ObjectSchema<
    serializers.CreateCollectionResponseOnChain.Raw,
    Crossmint.CreateCollectionResponseOnChain
> = core.serialization.object({
    chain: core.serialization.string().optional(),
    type: core.serialization.string().optional(),
});

export declare namespace CreateCollectionResponseOnChain {
    interface Raw {
        chain?: string | null;
        type?: string | null;
    }
}
