/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { CreateCollectionResponseMetadata } from "./CreateCollectionResponseMetadata";
import { CreateCollectionResponseOnChain } from "./CreateCollectionResponseOnChain";

export const CreateCollectionResponse: core.serialization.ObjectSchema<
    serializers.CreateCollectionResponse.Raw,
    Crossmint.CreateCollectionResponse
> = core.serialization.object({
    id: core.serialization.string().optional(),
    metadata: CreateCollectionResponseMetadata.optional(),
    fungibility: core.serialization.string().optional(),
    onChain: CreateCollectionResponseOnChain.optional(),
    actionId: core.serialization.string().optional(),
});

export declare namespace CreateCollectionResponse {
    interface Raw {
        id?: string | null;
        metadata?: CreateCollectionResponseMetadata.Raw | null;
        fungibility?: string | null;
        onChain?: CreateCollectionResponseOnChain.Raw | null;
        actionId?: string | null;
    }
}
