/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const CreateTemplateBodyOnChain: core.serialization.ObjectSchema<
    serializers.CreateTemplateBodyOnChain.Raw,
    Crossmint.CreateTemplateBodyOnChain
> = core.serialization.object({
    tokenId: core.serialization.string().optional(),
});

export declare namespace CreateTemplateBodyOnChain {
    interface Raw {
        tokenId?: string | null;
    }
}
