/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { CreateTemplateBodyMetadata } from "./CreateTemplateBodyMetadata";
import { CreateTemplateBodyOnChain } from "./CreateTemplateBodyOnChain";
import { CreateTemplateBodySupply } from "./CreateTemplateBodySupply";
import { ReuploadLinkedFiles } from "./ReuploadLinkedFiles";

export const CreateTemplateBody: core.serialization.ObjectSchema<
    serializers.CreateTemplateBody.Raw,
    Crossmint.CreateTemplateBody
> = core.serialization.object({
    metadata: CreateTemplateBodyMetadata.optional(),
    onChain: CreateTemplateBodyOnChain.optional(),
    supply: CreateTemplateBodySupply.optional(),
    reuploadLinkedFiles: ReuploadLinkedFiles.optional(),
});

export declare namespace CreateTemplateBody {
    interface Raw {
        metadata?: CreateTemplateBodyMetadata.Raw | null;
        onChain?: CreateTemplateBodyOnChain.Raw | null;
        supply?: CreateTemplateBodySupply.Raw | null;
        reuploadLinkedFiles?: ReuploadLinkedFiles.Raw | null;
    }
}
