/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const CreateCollectionBodyChain: core.serialization.Schema<
    serializers.CreateCollectionBodyChain.Raw,
    Crossmint.CreateCollectionBodyChain
> = core.serialization.enum_([
    "aptos",
    "arbitrum",
    "arbitrum-sepolia",
    "astar-zkevm",
    "base",
    "base-sepolia",
    "bsc",
    "ethereum",
    "ethereum-sepolia",
    "optimism",
    "optimism-sepolia",
    "polygon",
    "polygon-amoy",
    "skale-nebula",
    "skale-nebula-testnet",
    "solana",
    "zkyoto",
    "zora",
    "zora-sepolia",
]);

export declare namespace CreateCollectionBodyChain {
    type Raw =
        | "aptos"
        | "arbitrum"
        | "arbitrum-sepolia"
        | "astar-zkevm"
        | "base"
        | "base-sepolia"
        | "bsc"
        | "ethereum"
        | "ethereum-sepolia"
        | "optimism"
        | "optimism-sepolia"
        | "polygon"
        | "polygon-amoy"
        | "skale-nebula"
        | "skale-nebula-testnet"
        | "solana"
        | "zkyoto"
        | "zora"
        | "zora-sepolia";
}
