/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const CreateCollectionBodyMetadata: core.serialization.ObjectSchema<
    serializers.CreateCollectionBodyMetadata.Raw,
    Crossmint.CreateCollectionBodyMetadata
> = core.serialization.object({
    name: core.serialization.string(),
    imageUrl: core.serialization.string().optional(),
    description: core.serialization.string(),
    symbol: core.serialization.string().optional(),
});

export declare namespace CreateCollectionBodyMetadata {
    interface Raw {
        name: string;
        imageUrl?: string | null;
        description: string;
        symbol?: string | null;
    }
}
