/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { EditNftResponseData } from "./EditNftResponseData";

export const EditNftResponse: core.serialization.ObjectSchema<
    serializers.EditNftResponse.Raw,
    Crossmint.EditNftResponse
> = core.serialization.object({
    actionId: core.serialization.string().optional(),
    action: core.serialization.string().optional(),
    status: core.serialization.string().optional(),
    data: EditNftResponseData.optional(),
    startedAt: core.serialization.date().optional(),
    completedAt: core.serialization.date().optional(),
    resource: core.serialization.string().optional(),
});

export declare namespace EditNftResponse {
    interface Raw {
        actionId?: string | null;
        action?: string | null;
        status?: string | null;
        data?: EditNftResponseData.Raw | null;
        startedAt?: string | null;
        completedAt?: string | null;
        resource?: string | null;
    }
}
