/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { EditNftResponseDataTokenOwner } from "./EditNftResponseDataTokenOwner";

export const EditNftResponseDataToken: core.serialization.ObjectSchema<
    serializers.EditNftResponseDataToken.Raw,
    Crossmint.EditNftResponseDataToken
> = core.serialization.object({
    id: core.serialization.string().optional(),
    owner: EditNftResponseDataTokenOwner.optional(),
    tokenId: core.serialization.string().optional(),
});

export declare namespace EditNftResponseDataToken {
    interface Raw {
        id?: string | null;
        owner?: EditNftResponseDataTokenOwner.Raw | null;
        tokenId?: string | null;
    }
}
