/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const Email: core.serialization.ObjectSchema<serializers.Email.Raw, Crossmint.Email> = core.serialization.object(
    {
        email: core.serialization.string(),
    }
);

export declare namespace Email {
    interface Raw {
        email: string;
    }
}
