/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const Error503Response: core.serialization.ObjectSchema<
    serializers.Error503Response.Raw,
    Crossmint.Error503Response
> = core.serialization.object({
    error: core.serialization.boolean().optional(),
    message: core.serialization.string().optional(),
});

export declare namespace Error503Response {
    interface Raw {
        error?: boolean | null;
        message?: string | null;
    }
}
