/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { PaymentZeroMethod } from "./PaymentZeroMethod";
import { PaymentZeroCurrency } from "./PaymentZeroCurrency";

export const Evm: core.serialization.ObjectSchema<serializers.Evm.Raw, Crossmint.Evm> = core.serialization.object({
    receiptEmail: core.serialization.string().optional(),
    method: PaymentZeroMethod,
    currency: PaymentZeroCurrency,
    payerAddress: core.serialization.string().optional(),
});

export declare namespace Evm {
    interface Raw {
        receiptEmail?: string | null;
        method: PaymentZeroMethod.Raw;
        currency: PaymentZeroCurrency.Raw;
        payerAddress?: string | null;
    }
}
