/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const EvmChains: core.serialization.Schema<serializers.EvmChains.Raw, Crossmint.EvmChains> =
    core.serialization.enum_([
        "arbitrum",
        "arbitrumnova",
        "arbitrum-sepolia",
        "base",
        "base-sepolia",
        "bsc",
        "ethereum",
        "ethereum-sepolia",
        "optimism",
        "optimism-sepolia",
        "polygon",
        "polygon-amoy",
        "zkyoto",
        "zora",
        "zora-sepolia",
    ]);

export declare namespace EvmChains {
    type Raw =
        | "arbitrum"
        | "arbitrumnova"
        | "arbitrum-sepolia"
        | "base"
        | "base-sepolia"
        | "bsc"
        | "ethereum"
        | "ethereum-sepolia"
        | "optimism"
        | "optimism-sepolia"
        | "polygon"
        | "polygon-amoy"
        | "zkyoto"
        | "zora"
        | "zora-sepolia";
}
