/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { EvmPaymentMethods } from "./EvmPaymentMethods";
import { EvmPaymentCurrency } from "./EvmPaymentCurrency";

export const EvmPayment: core.serialization.ObjectSchema<serializers.EvmPayment.Raw, Crossmint.EvmPayment> =
    core.serialization.object({
        receiptEmail: core.serialization.string().optional(),
        method: EvmPaymentMethods,
        currency: EvmPaymentCurrency,
        payerAddress: core.serialization.string().optional(),
    });

export declare namespace EvmPayment {
    interface Raw {
        receiptEmail?: string | null;
        method: EvmPaymentMethods.Raw;
        currency: EvmPaymentCurrency.Raw;
        payerAddress?: string | null;
    }
}
