/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const ExternalCollection: core.serialization.ObjectSchema<
    serializers.ExternalCollection.Raw,
    Crossmint.ExternalCollection
> = core.serialization.object({
    message: core.serialization.string().optional(),
});

export declare namespace ExternalCollection {
    interface Raw {
        message?: string | null;
    }
}
