/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { PaymentCurrencyCurrency } from "./PaymentCurrencyCurrency";

export const Fiat: core.serialization.ObjectSchema<serializers.Fiat.Raw, Crossmint.Fiat> = core.serialization.object({
    receiptEmail: core.serialization.string().optional(),
    method: core.serialization.stringLiteral("stripe-payment-element"),
    currency: PaymentCurrencyCurrency.optional(),
});

export declare namespace Fiat {
    interface Raw {
        receiptEmail?: string | null;
        method: "stripe-payment-element";
        currency?: PaymentCurrencyCurrency.Raw | null;
    }
}
