/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { FiatPaymentCurrency } from "./FiatPaymentCurrency";

export const FiatPayment: core.serialization.ObjectSchema<serializers.FiatPayment.Raw, Crossmint.FiatPayment> =
    core.serialization.object({
        receiptEmail: core.serialization.string().optional(),
        method: core.serialization.stringLiteral("stripe-payment-element"),
        currency: FiatPaymentCurrency.optional(),
    });

export declare namespace FiatPayment {
    interface Raw {
        receiptEmail?: string | null;
        method: "stripe-payment-element";
        currency?: FiatPaymentCurrency.Raw | null;
    }
}
