/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { GetCollectionResponseMetadata } from "./GetCollectionResponseMetadata";
import { GetCollectionResponseOnChain } from "./GetCollectionResponseOnChain";
import { GetCollectionResponsePayments } from "./GetCollectionResponsePayments";

export const GetCollectionResponse: core.serialization.ObjectSchema<
    serializers.GetCollectionResponse.Raw,
    Crossmint.GetCollectionResponse
> = core.serialization.object({
    id: core.serialization.string().optional(),
    metadata: GetCollectionResponseMetadata.optional(),
    fungibility: core.serialization.string().optional(),
    onChain: GetCollectionResponseOnChain.optional(),
    supplyLimit: core.serialization.number().optional(),
    payments: GetCollectionResponsePayments.optional(),
});

export declare namespace GetCollectionResponse {
    interface Raw {
        id?: string | null;
        metadata?: GetCollectionResponseMetadata.Raw | null;
        fungibility?: string | null;
        onChain?: GetCollectionResponseOnChain.Raw | null;
        supplyLimit?: number | null;
        payments?: GetCollectionResponsePayments.Raw | null;
    }
}
