/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const GetCollectionResponseOnChain: core.serialization.ObjectSchema<
    serializers.GetCollectionResponseOnChain.Raw,
    Crossmint.GetCollectionResponseOnChain
> = core.serialization.object({
    chain: core.serialization.string().optional(),
    type: core.serialization.string().optional(),
    contractAddress: core.serialization.string().optional(),
});

export declare namespace GetCollectionResponseOnChain {
    interface Raw {
        chain?: string | null;
        type?: string | null;
        contractAddress?: string | null;
    }
}
