/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const LineItemsCallDataCallData: core.serialization.ObjectSchema<
    serializers.LineItemsCallDataCallData.Raw,
    Crossmint.LineItemsCallDataCallData
> = core.serialization.object({
    totalPrice: core.serialization.string().optional(),
});

export declare namespace LineItemsCallDataCallData {
    interface Raw {
        totalPrice?: string | null;
    }
}
