/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { NftObjectEvm } from "./NftObjectEvm";

export const MintResponseEvm200Subsequent: core.serialization.ObjectSchema<
    serializers.MintResponseEvm200Subsequent.Raw,
    Crossmint.MintResponseEvm200Subsequent
> = core.serialization
    .object({
        actionId: core.serialization.string().optional(),
    })
    .extend(NftObjectEvm);

export declare namespace MintResponseEvm200Subsequent {
    interface Raw extends NftObjectEvm.Raw {
        actionId?: string | null;
    }
}
