/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { MintStatusStatus } from "./MintStatusStatus";

export const MintStatus: core.serialization.ObjectSchema<serializers.MintStatus.Raw, Crossmint.MintStatus> =
    core.serialization.object({
        status: MintStatusStatus.optional(),
        mintAddress: core.serialization.string().optional(),
        walletAddress: core.serialization.string().optional(),
        passThroughArgs: core.serialization.string().optional(),
    });

export declare namespace MintStatus {
    interface Raw {
        status?: MintStatusStatus.Raw | null;
        mintAddress?: string | null;
        walletAddress?: string | null;
        passThroughArgs?: string | null;
    }
}
