/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const MintStatusStatus: core.serialization.Schema<serializers.MintStatusStatus.Raw, Crossmint.MintStatusStatus> =
    core.serialization.enum_(["minting", "success", "error"]);

export declare namespace MintStatusStatus {
    type Raw = "minting" | "success" | "error";
}
