/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { NftObjectSolana } from "./NftObjectSolana";

export const MintResponseSolana200Subsequent: core.serialization.ObjectSchema<
    serializers.MintResponseSolana200Subsequent.Raw,
    Crossmint.MintResponseSolana200Subsequent
> = core.serialization
    .object({
        actionId: core.serialization.string().optional(),
    })
    .extend(NftObjectSolana);

export declare namespace MintResponseSolana200Subsequent {
    interface Raw extends NftObjectSolana.Raw {
        actionId?: string | null;
    }
}
