/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { MintResponseSolana200OnChain } from "./MintResponseSolana200OnChain";

export const MintResponseSolana200: core.serialization.ObjectSchema<
    serializers.MintResponseSolana200.Raw,
    Crossmint.MintResponseSolana200
> = core.serialization.object({
    id: core.serialization.string().optional(),
    onChain: MintResponseSolana200OnChain.optional(),
    actionId: core.serialization.string().optional(),
});

export declare namespace MintResponseSolana200 {
    interface Raw {
        id?: string | null;
        onChain?: MintResponseSolana200OnChain.Raw | null;
        actionId?: string | null;
    }
}
