/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { NftAttributesItemValue } from "./NftAttributesItemValue";

export const NftAttributesItem: core.serialization.ObjectSchema<
    serializers.NftAttributesItem.Raw,
    Crossmint.NftAttributesItem
> = core.serialization.object({
    traitType: core.serialization.string().optional(),
    value: NftAttributesItemValue.optional(),
});

export declare namespace NftAttributesItem {
    interface Raw {
        traitType?: string | null;
        value?: NftAttributesItemValue.Raw | null;
    }
}
