/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const NftCollection: core.serialization.ObjectSchema<serializers.NftCollection.Raw, Crossmint.NftCollection> =
    core.serialization.object({
        name: core.serialization.string().optional(),
        family: core.serialization.string().optional(),
    });

export declare namespace NftCollection {
    interface Raw {
        name?: string | null;
        family?: string | null;
    }
}
