/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { NftcarItemMetadata } from "./NftcarItemMetadata";

export const NftcarItem: core.serialization.ObjectSchema<serializers.NftcarItem.Raw, Crossmint.NftcarItem> =
    core.serialization.object({
        chain: core.serialization.string().optional(),
        assetId: core.serialization.string().optional(),
        metadata: NftcarItemMetadata.optional(),
        locator: core.serialization.string().optional(),
    });

export declare namespace NftcarItem {
    interface Raw {
        chain?: string | null;
        assetId?: string | null;
        metadata?: NftcarItemMetadata.Raw | null;
        locator?: string | null;
    }
}
