/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { NftevmItemMetadata } from "./NftevmItemMetadata";

export const NftevmItem: core.serialization.ObjectSchema<serializers.NftevmItem.Raw, Crossmint.NftevmItem> =
    core.serialization.object({
        chain: core.serialization.string().optional(),
        contractAddress: core.serialization.string().optional(),
        tokenId: core.serialization.string().optional(),
        metadata: NftevmItemMetadata.optional(),
        locator: core.serialization.string().optional(),
        tokenStandard: core.serialization.string().optional(),
    });

export declare namespace NftevmItem {
    interface Raw {
        chain?: string | null;
        contractAddress?: string | null;
        tokenId?: string | null;
        metadata?: NftevmItemMetadata.Raw | null;
        locator?: string | null;
        tokenStandard?: string | null;
    }
}
