/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const NftevmItemMetadataAttributesItem: core.serialization.ObjectSchema<
    serializers.NftevmItemMetadataAttributesItem.Raw,
    Crossmint.NftevmItemMetadataAttributesItem
> = core.serialization.object({
    traitType: core.serialization.property("trait_type", core.serialization.string().optional()),
    value: core.serialization.string().optional(),
    displayType: core.serialization.property("display_type", core.serialization.string().optional()),
});

export declare namespace NftevmItemMetadataAttributesItem {
    interface Raw {
        trait_type?: string | null;
        value?: string | null;
        display_type?: string | null;
    }
}
