/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { NftevmItemMetadataAttributesItem } from "./NftevmItemMetadataAttributesItem";

export const NftevmItemMetadata: core.serialization.ObjectSchema<
    serializers.NftevmItemMetadata.Raw,
    Crossmint.NftevmItemMetadata
> = core.serialization.object({
    attributes: core.serialization.list(NftevmItemMetadataAttributesItem).optional(),
    collection: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    description: core.serialization.string().optional(),
    image: core.serialization.string().optional(),
    animationUrl: core.serialization.property("animation_url", core.serialization.string().optional()),
    name: core.serialization.string().optional(),
});

export declare namespace NftevmItemMetadata {
    interface Raw {
        attributes?: NftevmItemMetadataAttributesItem.Raw[] | null;
        collection?: Record<string, unknown> | null;
        description?: string | null;
        image?: string | null;
        animation_url?: string | null;
        name?: string | null;
    }
}
