/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { NftMetadataAttributesItemDisplayType } from "./NftMetadataAttributesItemDisplayType";

export const NftMetadataAttributesItem: core.serialization.ObjectSchema<
    serializers.NftMetadataAttributesItem.Raw,
    Crossmint.NftMetadataAttributesItem
> = core.serialization.object({
    displayType: core.serialization.property("display_type", NftMetadataAttributesItemDisplayType.optional()),
    traitType: core.serialization.property("trait_type", core.serialization.string()),
    value: core.serialization.string(),
});

export declare namespace NftMetadataAttributesItem {
    interface Raw {
        display_type?: NftMetadataAttributesItemDisplayType.Raw | null;
        trait_type: string;
        value: string;
    }
}
