/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { NftMetadataAttributesItem } from "./NftMetadataAttributesItem";

export const NftMetadata: core.serialization.ObjectSchema<serializers.NftMetadata.Raw, Crossmint.NftMetadata> =
    core.serialization.object({
        name: core.serialization.string(),
        image: core.serialization.string(),
        description: core.serialization.string(),
        animationUrl: core.serialization.property("animation_url", core.serialization.string().optional()),
        attributes: core.serialization.list(NftMetadataAttributesItem).optional(),
    });

export declare namespace NftMetadata {
    interface Raw {
        name: string;
        image: string;
        description: string;
        animation_url?: string | null;
        attributes?: NftMetadataAttributesItem.Raw[] | null;
    }
}
