/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { NftMetadataSolanaAttributesItemDisplayType } from "./NftMetadataSolanaAttributesItemDisplayType";

export const NftMetadataSolanaAttributesItem: core.serialization.ObjectSchema<
    serializers.NftMetadataSolanaAttributesItem.Raw,
    Crossmint.NftMetadataSolanaAttributesItem
> = core.serialization.object({
    displayType: core.serialization.property("display_type", NftMetadataSolanaAttributesItemDisplayType.optional()),
    traitType: core.serialization.property("trait_type", core.serialization.string()),
    value: core.serialization.string(),
});

export declare namespace NftMetadataSolanaAttributesItem {
    interface Raw {
        display_type?: NftMetadataSolanaAttributesItemDisplayType.Raw | null;
        trait_type: string;
        value: string;
    }
}
