/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { NftMetadataSolanaAttributesItem } from "./NftMetadataSolanaAttributesItem";

export const NftMetadataSolana: core.serialization.ObjectSchema<
    serializers.NftMetadataSolana.Raw,
    Crossmint.NftMetadataSolana
> = core.serialization.object({
    name: core.serialization.string(),
    image: core.serialization.string(),
    description: core.serialization.string(),
    attributes: core.serialization.list(NftMetadataSolanaAttributesItem).optional(),
});

export declare namespace NftMetadataSolana {
    interface Raw {
        name: string;
        image: string;
        description: string;
        attributes?: NftMetadataSolanaAttributesItem.Raw[] | null;
    }
}
