/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const NftMetadataSolanaAttributesItemDisplayType: core.serialization.Schema<
    serializers.NftMetadataSolanaAttributesItemDisplayType.Raw,
    Crossmint.NftMetadataSolanaAttributesItemDisplayType
> = core.serialization.enum_(["boost_number", "boost_percentage", "number"]);

export declare namespace NftMetadataSolanaAttributesItemDisplayType {
    type Raw = "boost_number" | "boost_percentage" | "number";
}
