/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const NftMetadataOptionsName: core.serialization.ObjectSchema<
    serializers.NftMetadataOptionsName.Raw,
    Crossmint.NftMetadataOptionsName
> = core.serialization.object({
    uri: core.serialization.string(),
    name: core.serialization.string(),
});

export declare namespace NftMetadataOptionsName {
    interface Raw {
        uri: string;
        name: string;
    }
}
