/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { NftMetadata } from "./NftMetadata";
import { NftMetadataSolana } from "./NftMetadataSolana";
import { NftMetadataOptionsName } from "./NftMetadataOptionsName";

export const NftMetadataOptions: core.serialization.Schema<
    serializers.NftMetadataOptions.Raw,
    Crossmint.NftMetadataOptions
> = core.serialization.undiscriminatedUnion([
    NftMetadata,
    core.serialization.string(),
    NftMetadataSolana,
    NftMetadataOptionsName,
]);

export declare namespace NftMetadataOptions {
    type Raw = NftMetadata.Raw | string | NftMetadataSolana.Raw | NftMetadataOptionsName.Raw;
}
