/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const NftObjectSolanaOnChain: core.serialization.ObjectSchema<
    serializers.NftObjectSolanaOnChain.Raw,
    Crossmint.NftObjectSolanaOnChain
> = core.serialization.object({
    status: core.serialization.string().optional(),
    mintHash: core.serialization.string().optional(),
    txId: core.serialization.string().optional(),
    owner: core.serialization.string().optional(),
    chain: core.serialization.string().optional(),
});

export declare namespace NftObjectSolanaOnChain {
    interface Raw {
        status?: string | null;
        mintHash?: string | null;
        txId?: string | null;
        owner?: string | null;
        chain?: string | null;
    }
}
