/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const NftObjectEvmOnChain: core.serialization.ObjectSchema<
    serializers.NftObjectEvmOnChain.Raw,
    Crossmint.NftObjectEvmOnChain
> = core.serialization.object({
    status: core.serialization.string().optional(),
    tokenId: core.serialization.string().optional(),
    owner: core.serialization.string().optional(),
    txId: core.serialization.string().optional(),
    contractAddress: core.serialization.string().optional(),
    chain: core.serialization.string().optional(),
});

export declare namespace NftObjectEvmOnChain {
    interface Raw {
        status?: string | null;
        tokenId?: string | null;
        owner?: string | null;
        txId?: string | null;
        contractAddress?: string | null;
        chain?: string | null;
    }
}
