/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const NftObjectSolanaMetadataPropertiesCreatorsItem: core.serialization.ObjectSchema<
    serializers.NftObjectSolanaMetadataPropertiesCreatorsItem.Raw,
    Crossmint.NftObjectSolanaMetadataPropertiesCreatorsItem
> = core.serialization.object({
    address: core.serialization.string().optional(),
    verified: core.serialization.boolean().optional(),
    share: core.serialization.number().optional(),
});

export declare namespace NftObjectSolanaMetadataPropertiesCreatorsItem {
    interface Raw {
        address?: string | null;
        verified?: boolean | null;
        share?: number | null;
    }
}
