/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { NftObjectSolanaMetadataPropertiesFilesItem } from "./NftObjectSolanaMetadataPropertiesFilesItem";
import { NftObjectSolanaMetadataPropertiesCreatorsItem } from "./NftObjectSolanaMetadataPropertiesCreatorsItem";

export const NftObjectSolanaMetadataProperties: core.serialization.ObjectSchema<
    serializers.NftObjectSolanaMetadataProperties.Raw,
    Crossmint.NftObjectSolanaMetadataProperties
> = core.serialization.object({
    files: core.serialization.list(NftObjectSolanaMetadataPropertiesFilesItem).optional(),
    category: core.serialization.string().optional(),
    creators: core.serialization.list(NftObjectSolanaMetadataPropertiesCreatorsItem).optional(),
});

export declare namespace NftObjectSolanaMetadataProperties {
    interface Raw {
        files?: NftObjectSolanaMetadataPropertiesFilesItem.Raw[] | null;
        category?: string | null;
        creators?: NftObjectSolanaMetadataPropertiesCreatorsItem.Raw[] | null;
    }
}
