/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { NftObjectEvmMetadata } from "./NftObjectEvmMetadata";
import { NftObjectEvmOnChain } from "./NftObjectEvmOnChain";

export const NftObjectEvm: core.serialization.ObjectSchema<serializers.NftObjectEvm.Raw, Crossmint.NftObjectEvm> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        metadata: NftObjectEvmMetadata.optional(),
        onChain: NftObjectEvmOnChain.optional(),
    });

export declare namespace NftObjectEvm {
    interface Raw {
        id?: string | null;
        metadata?: NftObjectEvmMetadata.Raw | null;
        onChain?: NftObjectEvmOnChain.Raw | null;
    }
}
