/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const NftObjectSolanaMetadataPropertiesFilesItem: core.serialization.ObjectSchema<
    serializers.NftObjectSolanaMetadataPropertiesFilesItem.Raw,
    Crossmint.NftObjectSolanaMetadataPropertiesFilesItem
> = core.serialization.object({
    uri: core.serialization.string().optional(),
    type: core.serialization.string().optional(),
});

export declare namespace NftObjectSolanaMetadataPropertiesFilesItem {
    interface Raw {
        uri?: string | null;
        type?: string | null;
    }
}
