/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const NftPropertiesFilesItem: core.serialization.ObjectSchema<
    serializers.NftPropertiesFilesItem.Raw,
    Crossmint.NftPropertiesFilesItem
> = core.serialization.object({
    uri: core.serialization.string().optional(),
    type: core.serialization.string().optional(),
});

export declare namespace NftPropertiesFilesItem {
    interface Raw {
        uri?: string | null;
        type?: string | null;
    }
}
