/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const NftPropertiesCreatorsItem: core.serialization.ObjectSchema<
    serializers.NftPropertiesCreatorsItem.Raw,
    Crossmint.NftPropertiesCreatorsItem
> = core.serialization.object({
    address: core.serialization.string().optional(),
    share: core.serialization.number().optional(),
});

export declare namespace NftPropertiesCreatorsItem {
    interface Raw {
        address?: string | null;
        share?: number | null;
    }
}
