/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { NftsolItemMetadataAttributesItem } from "./NftsolItemMetadataAttributesItem";

export const NftsolItemMetadata: core.serialization.ObjectSchema<
    serializers.NftsolItemMetadata.Raw,
    Crossmint.NftsolItemMetadata
> = core.serialization.object({
    name: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    image: core.serialization.string().optional(),
    attributes: core.serialization.list(NftsolItemMetadataAttributesItem).optional(),
});

export declare namespace NftsolItemMetadata {
    interface Raw {
        name?: string | null;
        description?: string | null;
        image?: string | null;
        attributes?: NftsolItemMetadataAttributesItem.Raw[] | null;
    }
}
