/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { NftsolItemMetadataAttributesItemValue } from "./NftsolItemMetadataAttributesItemValue";

export const NftsolItemMetadataAttributesItem: core.serialization.ObjectSchema<
    serializers.NftsolItemMetadataAttributesItem.Raw,
    Crossmint.NftsolItemMetadataAttributesItem
> = core.serialization.object({
    value: NftsolItemMetadataAttributesItemValue.optional(),
    traitType: core.serialization.property("trait_type", core.serialization.string().optional()),
});

export declare namespace NftsolItemMetadataAttributesItem {
    interface Raw {
        value?: NftsolItemMetadataAttributesItemValue.Raw | null;
        trait_type?: string | null;
    }
}
