/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { NftsolItem } from "./NftsolItem";

export const NftSolana: core.serialization.Schema<serializers.NftSolana.Raw, Crossmint.NftSolana> =
    core.serialization.list(NftsolItem);

export declare namespace NftSolana {
    type Raw = NftsolItem.Raw[];
}
