/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const NftsolItemMetadataAttributesItemValue: core.serialization.Schema<
    serializers.NftsolItemMetadataAttributesItemValue.Raw,
    Crossmint.NftsolItemMetadataAttributesItemValue
> = core.serialization.undiscriminatedUnion([
    core.serialization.string(),
    core.serialization.number(),
    core.serialization.boolean(),
    core.serialization.record(core.serialization.string(), core.serialization.unknown()),
]);

export declare namespace NftsolItemMetadataAttributesItemValue {
    type Raw = string | number | boolean | Record<string, unknown>;
}
