/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const OrderObjectLineItemsItemCallData: core.serialization.ObjectSchema<
    serializers.OrderObjectLineItemsItemCallData.Raw,
    Crossmint.OrderObjectLineItemsItemCallData
> = core.serialization.object({
    quantity: core.serialization.number().optional(),
    additionalProperties: core.serialization.property("ADDITIONAL_PROPERTIES", core.serialization.string().optional()),
});

export declare namespace OrderObjectLineItemsItemCallData {
    interface Raw {
        quantity?: number | null;
        ADDITIONAL_PROPERTIES?: string | null;
    }
}
