/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { OrderObjectLineItemsItem } from "./OrderObjectLineItemsItem";
import { OrderObjectQuote } from "./OrderObjectQuote";
import { OrderObjectPayment } from "./OrderObjectPayment";

export const OrderObject: core.serialization.ObjectSchema<serializers.OrderObject.Raw, Crossmint.OrderObject> =
    core.serialization.object({
        orderId: core.serialization.string().optional(),
        phase: core.serialization.string().optional(),
        locale: core.serialization.string().optional(),
        lineItems: core.serialization.list(OrderObjectLineItemsItem).optional(),
        quote: OrderObjectQuote.optional(),
        payment: OrderObjectPayment.optional(),
    });

export declare namespace OrderObject {
    interface Raw {
        orderId?: string | null;
        phase?: string | null;
        locale?: string | null;
        lineItems?: OrderObjectLineItemsItem.Raw[] | null;
        quote?: OrderObjectQuote.Raw | null;
        payment?: OrderObjectPayment.Raw | null;
    }
}
