/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const OrderObjectLineItemsItemQuoteChargesUnit: core.serialization.ObjectSchema<
    serializers.OrderObjectLineItemsItemQuoteChargesUnit.Raw,
    Crossmint.OrderObjectLineItemsItemQuoteChargesUnit
> = core.serialization.object({
    amount: core.serialization.string().optional(),
    currency: core.serialization.string().optional(),
});

export declare namespace OrderObjectLineItemsItemQuoteChargesUnit {
    interface Raw {
        amount?: string | null;
        currency?: string | null;
    }
}
