/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { OrderObjectLineItemsItemQuoteChargesUnit } from "./OrderObjectLineItemsItemQuoteChargesUnit";

export const OrderObjectLineItemsItemQuoteCharges: core.serialization.ObjectSchema<
    serializers.OrderObjectLineItemsItemQuoteCharges.Raw,
    Crossmint.OrderObjectLineItemsItemQuoteCharges
> = core.serialization.object({
    unit: OrderObjectLineItemsItemQuoteChargesUnit.optional(),
});

export declare namespace OrderObjectLineItemsItemQuoteCharges {
    interface Raw {
        unit?: OrderObjectLineItemsItemQuoteChargesUnit.Raw | null;
    }
}
