/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { OrderObjectPaymentPreparation } from "./OrderObjectPaymentPreparation";

export const OrderObjectPayment: core.serialization.ObjectSchema<
    serializers.OrderObjectPayment.Raw,
    Crossmint.OrderObjectPayment
> = core.serialization.object({
    status: core.serialization.string().optional(),
    method: core.serialization.string().optional(),
    currency: core.serialization.string().optional(),
    preparation: OrderObjectPaymentPreparation.optional(),
});

export declare namespace OrderObjectPayment {
    interface Raw {
        status?: string | null;
        method?: string | null;
        currency?: string | null;
        preparation?: OrderObjectPaymentPreparation.Raw | null;
    }
}
