/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const OrderObjectLineItemsItemMetadata: core.serialization.ObjectSchema<
    serializers.OrderObjectLineItemsItemMetadata.Raw,
    Crossmint.OrderObjectLineItemsItemMetadata
> = core.serialization.object({
    name: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    imageUrl: core.serialization.string().optional(),
});

export declare namespace OrderObjectLineItemsItemMetadata {
    interface Raw {
        name?: string | null;
        description?: string | null;
        imageUrl?: string | null;
    }
}
