/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { OrderObjectLineItemsItemCallData } from "./OrderObjectLineItemsItemCallData";
import { OrderObjectLineItemsItemMetadata } from "./OrderObjectLineItemsItemMetadata";
import { OrderObjectLineItemsItemQuote } from "./OrderObjectLineItemsItemQuote";
import { OrderObjectLineItemsItemDelivery } from "./OrderObjectLineItemsItemDelivery";

export const OrderObjectLineItemsItem: core.serialization.ObjectSchema<
    serializers.OrderObjectLineItemsItem.Raw,
    Crossmint.OrderObjectLineItemsItem
> = core.serialization.object({
    chain: core.serialization.string().optional(),
    quantity: core.serialization.number().optional(),
    callData: OrderObjectLineItemsItemCallData.optional(),
    metadata: OrderObjectLineItemsItemMetadata.optional(),
    quote: OrderObjectLineItemsItemQuote.optional(),
    delivery: OrderObjectLineItemsItemDelivery.optional(),
});

export declare namespace OrderObjectLineItemsItem {
    interface Raw {
        chain?: string | null;
        quantity?: number | null;
        callData?: OrderObjectLineItemsItemCallData.Raw | null;
        metadata?: OrderObjectLineItemsItemMetadata.Raw | null;
        quote?: OrderObjectLineItemsItemQuote.Raw | null;
        delivery?: OrderObjectLineItemsItemDelivery.Raw | null;
    }
}
