/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { OrderObjectLineItemsItemQuoteCharges } from "./OrderObjectLineItemsItemQuoteCharges";
import { OrderObjectLineItemsItemQuoteTotalPrice } from "./OrderObjectLineItemsItemQuoteTotalPrice";

export const OrderObjectLineItemsItemQuote: core.serialization.ObjectSchema<
    serializers.OrderObjectLineItemsItemQuote.Raw,
    Crossmint.OrderObjectLineItemsItemQuote
> = core.serialization.object({
    status: core.serialization.string().optional(),
    charges: OrderObjectLineItemsItemQuoteCharges.optional(),
    totalPrice: OrderObjectLineItemsItemQuoteTotalPrice.optional(),
});

export declare namespace OrderObjectLineItemsItemQuote {
    interface Raw {
        status?: string | null;
        charges?: OrderObjectLineItemsItemQuoteCharges.Raw | null;
        totalPrice?: OrderObjectLineItemsItemQuoteTotalPrice.Raw | null;
    }
}
