/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { OrderObjectQuoteTotalPrice } from "./OrderObjectQuoteTotalPrice";

export const OrderObjectQuote: core.serialization.ObjectSchema<
    serializers.OrderObjectQuote.Raw,
    Crossmint.OrderObjectQuote
> = core.serialization.object({
    status: core.serialization.string().optional(),
    quotedAt: core.serialization.string().optional(),
    expiresAt: core.serialization.string().optional(),
    totalPrice: OrderObjectQuoteTotalPrice.optional(),
});

export declare namespace OrderObjectQuote {
    interface Raw {
        status?: string | null;
        quotedAt?: string | null;
        expiresAt?: string | null;
        totalPrice?: OrderObjectQuoteTotalPrice.Raw | null;
    }
}
