/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const OutdatedContract: core.serialization.ObjectSchema<
    serializers.OutdatedContract.Raw,
    Crossmint.OutdatedContract
> = core.serialization.object({
    message: core.serialization.string().optional(),
});

export declare namespace OutdatedContract {
    interface Raw {
        message?: string | null;
    }
}
