/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const PaymentsObject: core.serialization.ObjectSchema<serializers.PaymentsObject.Raw, Crossmint.PaymentsObject> =
    core.serialization.object({
        price: core.serialization.string().optional(),
        recipientAddress: core.serialization.string().optional(),
        currency: core.serialization.string().optional(),
    });

export declare namespace PaymentsObject {
    interface Raw {
        price?: string | null;
        recipientAddress?: string | null;
        currency?: string | null;
    }
}
