/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { EvmPaymentMethods } from "./EvmPaymentMethods";
import { SolanaPaymentMethods } from "./SolanaPaymentMethods";
import { FiatPaymentMethods } from "./FiatPaymentMethods";

export const Payment: core.serialization.Schema<serializers.Payment.Raw, Crossmint.Payment> =
    core.serialization.undiscriminatedUnion([EvmPaymentMethods, SolanaPaymentMethods, FiatPaymentMethods]);

export declare namespace Payment {
    type Raw = EvmPaymentMethods.Raw | SolanaPaymentMethods.Raw | FiatPaymentMethods.Raw;
}
