/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const PaymentZeroCurrency: core.serialization.Schema<
    serializers.PaymentZeroCurrency.Raw,
    Crossmint.PaymentZeroCurrency
> = core.serialization.enum_(["eth", "usdc", "degen", "brett", "toshi"]);

export declare namespace PaymentZeroCurrency {
    type Raw = "eth" | "usdc" | "degen" | "brett" | "toshi";
}
