/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const PaymentOneCurrency: core.serialization.Schema<
    serializers.PaymentOneCurrency.Raw,
    Crossmint.PaymentOneCurrency
> = core.serialization.enum_(["sol", "usdc", "bonk", "wif", "mother"]);

export declare namespace PaymentOneCurrency {
    type Raw = "sol" | "usdc" | "bonk" | "wif" | "mother";
}
