/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { Email } from "./Email";
import { Wallet } from "./Wallet";

export const Recipient: core.serialization.Schema<serializers.Recipient.Raw, Crossmint.Recipient> =
    core.serialization.undiscriminatedUnion([Email, Wallet]);

export declare namespace Recipient {
    type Raw = Email.Raw | Wallet.Raw;
}
