/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const Response503: core.serialization.ObjectSchema<serializers.Response503.Raw, Crossmint.Response503> =
    core.serialization.object({
        error: core.serialization.boolean().optional(),
        message: core.serialization.string().optional(),
    });

export declare namespace Response503 {
    interface Raw {
        error?: boolean | null;
        message?: string | null;
    }
}
