/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const ReuploadLinkedFiles: core.serialization.Schema<
    serializers.ReuploadLinkedFiles.Raw,
    Crossmint.ReuploadLinkedFiles
> = core.serialization.boolean();

export declare namespace ReuploadLinkedFiles {
    type Raw = boolean;
}
