/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const SftCollection: core.serialization.ObjectSchema<serializers.SftCollection.Raw, Crossmint.SftCollection> =
    core.serialization.object({
        message: core.serialization.string().optional(),
    });

export declare namespace SftCollection {
    interface Raw {
        message?: string | null;
    }
}
