/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const SolanaPaymentCurrency: core.serialization.Schema<
    serializers.SolanaPaymentCurrency.Raw,
    Crossmint.SolanaPaymentCurrency
> = core.serialization.enum_(["sol", "usdc", "bonk", "wif", "mother"]);

export declare namespace SolanaPaymentCurrency {
    type Raw = "sol" | "usdc" | "bonk" | "wif" | "mother";
}
