/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { PaymentOneCurrency } from "./PaymentOneCurrency";

export const SolanaPaymentMethods: core.serialization.ObjectSchema<
    serializers.SolanaPaymentMethods.Raw,
    Crossmint.SolanaPaymentMethods
> = core.serialization.object({
    receiptEmail: core.serialization.string().optional(),
    method: core.serialization.stringLiteral("solana"),
    currency: PaymentOneCurrency,
    payerAddress: core.serialization.string().optional(),
});

export declare namespace SolanaPaymentMethods {
    interface Raw {
        receiptEmail?: string | null;
        method: "solana";
        currency: PaymentOneCurrency.Raw;
        payerAddress?: string | null;
    }
}
