/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { SolanaPaymentCurrency } from "./SolanaPaymentCurrency";

export const SolanaPayment: core.serialization.ObjectSchema<serializers.SolanaPayment.Raw, Crossmint.SolanaPayment> =
    core.serialization.object({
        receiptEmail: core.serialization.string().optional(),
        method: core.serialization.stringLiteral("solana"),
        currency: SolanaPaymentCurrency,
        payerAddress: core.serialization.string().optional(),
    });

export declare namespace SolanaPayment {
    interface Raw {
        receiptEmail?: string | null;
        method: "solana";
        currency: SolanaPaymentCurrency.Raw;
        payerAddress?: string | null;
    }
}
