/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const SupplySupply: core.serialization.ObjectSchema<serializers.SupplySupply.Raw, Crossmint.SupplySupply> =
    core.serialization.object({
        limit: core.serialization.number().optional(),
    });

export declare namespace SupplySupply {
    interface Raw {
        limit?: number | null;
    }
}
