/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const TemplateResponseOnChain: core.serialization.ObjectSchema<
    serializers.TemplateResponseOnChain.Raw,
    Crossmint.TemplateResponseOnChain
> = core.serialization.object({
    tokenId: core.serialization.number().optional(),
});

export declare namespace TemplateResponseOnChain {
    interface Raw {
        tokenId?: number | null;
    }
}
