/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const TemplateResponseSupply: core.serialization.ObjectSchema<
    serializers.TemplateResponseSupply.Raw,
    Crossmint.TemplateResponseSupply
> = core.serialization.object({
    limit: core.serialization.number().optional(),
    minted: core.serialization.number().optional(),
});

export declare namespace TemplateResponseSupply {
    interface Raw {
        limit?: number | null;
        minted?: number | null;
    }
}
