/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const TransferPendingVerification: core.serialization.ObjectSchema<
    serializers.TransferPendingVerification.Raw,
    Crossmint.TransferPendingVerification
> = core.serialization.object({
    personaUrl: core.serialization.string().optional(),
});

export declare namespace TransferPendingVerification {
    interface Raw {
        personaUrl?: string | null;
    }
}
