/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { UsageResponseData } from "./UsageResponseData";

export const UsageResponse: core.serialization.ObjectSchema<serializers.UsageResponse.Raw, Crossmint.UsageResponse> =
    core.serialization.object({
        data: UsageResponseData.optional(),
    });

export declare namespace UsageResponse {
    interface Raw {
        data?: UsageResponseData.Raw | null;
    }
}
