/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { UsageResponseDataUsage } from "./UsageResponseDataUsage";

export const UsageResponseData: core.serialization.ObjectSchema<
    serializers.UsageResponseData.Raw,
    Crossmint.UsageResponseData
> = core.serialization.object({
    dimension: core.serialization.string().optional(),
    usage: UsageResponseDataUsage.optional(),
});

export declare namespace UsageResponseData {
    interface Raw {
        dimension?: string | null;
        usage?: UsageResponseDataUsage.Raw | null;
    }
}
