/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const UsageResponseDataUsage: core.serialization.ObjectSchema<
    serializers.UsageResponseDataUsage.Raw,
    Crossmint.UsageResponseDataUsage
> = core.serialization.object({
    month: core.serialization.string().optional(),
    activeWallets: core.serialization.number().optional(),
});

export declare namespace UsageResponseDataUsage {
    interface Raw {
        month?: string | null;
        activeWallets?: number | null;
    }
}
