/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const ValidationError: core.serialization.ObjectSchema<
    serializers.ValidationError.Raw,
    Crossmint.ValidationError
> = core.serialization.object({
    index: core.serialization.number().optional(),
    id: core.serialization.string().optional(),
    message: core.serialization.string().optional(),
});

export declare namespace ValidationError {
    interface Raw {
        index?: number | null;
        id?: string | null;
        message?: string | null;
    }
}
