/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const VerificationRequestSent: core.serialization.ObjectSchema<
    serializers.VerificationRequestSent.Raw,
    Crossmint.VerificationRequestSent
> = core.serialization.object({
    message: core.serialization.string().optional(),
    actionId: core.serialization.string().optional(),
});

export declare namespace VerificationRequestSent {
    interface Raw {
        message?: string | null;
        actionId?: string | null;
    }
}
