/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";
import { EvmTransfer } from "./EvmTransfer";
import { Solana } from "./Solana";

export const WalletsRequest: core.serialization.Schema<serializers.WalletsRequest.Raw, Crossmint.WalletsRequest> =
    core.serialization.undiscriminatedUnion([EvmTransfer, Solana]);

export declare namespace WalletsRequest {
    type Raw = EvmTransfer.Raw | Solana.Raw;
}
