/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Crossmint from "../../api/index";
import * as core from "../../core";

export const Wallet: core.serialization.ObjectSchema<serializers.Wallet.Raw, Crossmint.Wallet> =
    core.serialization.object({
        chain: core.serialization.string().optional(),
        publicKey: core.serialization.string().optional(),
    });

export declare namespace Wallet {
    interface Raw {
        chain?: string | null;
        publicKey?: string | null;
    }
}
