/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../../../index";

export interface BatchMintNftRequestNftsItem {
    recipient?: Crossmint.Recipient;
    metadata?: Crossmint.NftMetadataOptions;
    compressed?: Crossmint.Compressed;
    /** **Optional** The idempotent identifier for the NFT */
    id?: string;
}
