/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../../../index";

export type MintNftRequest = Crossmint.Metadata | Crossmint.MintNftRequestTemplateId;
