/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../../../index";

export type MintNftResponse = Crossmint.MintResponseSolana200 | Crossmint.MintResponseEvm200;
