/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../../../index";

export interface MintSftResponseData {
    chain?: string;
    collection?: Crossmint.MintSftResponseDataCollection;
    recipient?: Crossmint.MintSftResponseDataRecipient;
    token?: Crossmint.MintSftResponseDataToken;
}
