/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../../../index";

export type MintNftIdempotentResponse =
    | Crossmint.MintResponseSolana200
    | Crossmint.MintResponseSolana200Subsequent
    | Crossmint.MintResponseEvm200
    | Crossmint.MintResponseEvm200Subsequent;
