/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../../../index";

export interface MintSftResponse {
    actionId?: string;
    action?: string;
    status?: string;
    data?: Crossmint.MintSftResponseData;
    startedAt?: string;
    resource?: string;
}
