/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";
import { NftMetadataOptions } from "../../../types/NftMetadataOptions";

export const Metadata: core.serialization.ObjectSchema<serializers.Metadata.Raw, Crossmint.Metadata> =
    core.serialization.object({
        metadata: NftMetadataOptions,
    });

export declare namespace Metadata {
    interface Raw {
        metadata: NftMetadataOptions.Raw;
    }
}
