/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";
import { Metadata } from "./Metadata";
import { MintNftRequestTemplateId } from "./MintNftRequestTemplateId";

export const MintNftRequest: core.serialization.Schema<serializers.MintNftRequest.Raw, Crossmint.MintNftRequest> =
    core.serialization.undiscriminatedUnion([Metadata, MintNftRequestTemplateId]);

export declare namespace MintNftRequest {
    type Raw = Metadata.Raw | MintNftRequestTemplateId.Raw;
}
