/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";

export const MintSftResponseDataToken: core.serialization.ObjectSchema<
    serializers.MintSftResponseDataToken.Raw,
    Crossmint.MintSftResponseDataToken
> = core.serialization.object({
    id: core.serialization.string().optional(),
});

export declare namespace MintSftResponseDataToken {
    interface Raw {
        id?: string | null;
    }
}
