/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";

export const MintNftRequestTemplateId: core.serialization.ObjectSchema<
    serializers.MintNftRequestTemplateId.Raw,
    Crossmint.MintNftRequestTemplateId
> = core.serialization.object({
    templateId: core.serialization.string(),
});

export declare namespace MintNftRequestTemplateId {
    interface Raw {
        templateId: string;
    }
}
