/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";
import { MintResponseSolana200 } from "../../../types/MintResponseSolana200";
import { MintResponseEvm200 } from "../../../types/MintResponseEvm200";

export const MintNftResponse: core.serialization.Schema<serializers.MintNftResponse.Raw, Crossmint.MintNftResponse> =
    core.serialization.undiscriminatedUnion([MintResponseSolana200, MintResponseEvm200]);

export declare namespace MintNftResponse {
    type Raw = MintResponseSolana200.Raw | MintResponseEvm200.Raw;
}
