/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Crossmint from "../../../../../api/index";
import * as core from "../../../../../core";
import { EditRoyaltyInformationRequestRecipientsItem } from "../../types/EditRoyaltyInformationRequestRecipientsItem";

export const EditRoyaltyInformationRequest: core.serialization.Schema<
    serializers.EditRoyaltyInformationRequest.Raw,
    Crossmint.EditRoyaltyInformationRequest
> = core.serialization.object({
    recipients: core.serialization.list(EditRoyaltyInformationRequestRecipientsItem).optional(),
});

export declare namespace EditRoyaltyInformationRequest {
    interface Raw {
        recipients?: EditRoyaltyInformationRequestRecipientsItem.Raw[] | null;
    }
}
