/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Crossmint from "../../../../../api/index";
import * as core from "../../../../../core";

export const SetTransferabilityRequest: core.serialization.Schema<
    serializers.SetTransferabilityRequest.Raw,
    Crossmint.SetTransferabilityRequest
> = core.serialization.object({
    value: core.serialization.boolean(),
});

export declare namespace SetTransferabilityRequest {
    interface Raw {
        value: boolean;
    }
}
