/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Crossmint from "../../../../../api/index";
import * as core from "../../../../../core";
import { PaymentsObject } from "../../../../types/PaymentsObject";

export const UpdateCollectionRequest: core.serialization.Schema<
    serializers.UpdateCollectionRequest.Raw,
    Crossmint.UpdateCollectionRequest
> = core.serialization.object({
    supplyLimit: core.serialization.number().optional(),
    payments: PaymentsObject.optional(),
});

export declare namespace UpdateCollectionRequest {
    interface Raw {
        supplyLimit?: number | null;
        payments?: PaymentsObject.Raw | null;
    }
}
