/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../../../index";

export interface GetActionStatusResponse {
    actionId?: string;
    action?: string;
    status?: string;
    data?: Crossmint.GetActionStatusResponseData;
    startedAt?: Date;
    resource?: string;
}
