/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Crossmint from "../../../../../api/index";
import * as core from "../../../../../core";
import { Recipient } from "../../../../types/Recipient";
import { Locale } from "../../../../types/Locale";
import { Payment } from "../../../../types/Payment";

export const OrderDto: core.serialization.Schema<serializers.OrderDto.Raw, Crossmint.OrderDto> =
    core.serialization.object({
        recipient: Recipient.optional(),
        locale: Locale.optional(),
        payment: Payment.optional(),
    });

export declare namespace OrderDto {
    interface Raw {
        recipient?: Recipient.Raw | null;
        locale?: Locale.Raw | null;
        payment?: Payment.Raw | null;
    }
}
