/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../../../index";

export interface Email {
    /** Provide an email for this wallet to be associated to */
    email: string;
    chain: Crossmint.AllChains;
}
