/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Evm {
    contractAddress: string;
    abi: string;
    mintFunctionName: string;
    /** The name of the `to` parameter in the mint function */
    toParamName: string;
    quantityParamName?: string;
}
