/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Crypto chain your NFT is on
 */
export type RegisterNftCollectionRequestChain = "solana" | "ethereum" | "polygon" | "bsc";

export const RegisterNftCollectionRequestChain = {
    Solana: "solana",
    Ethereum: "ethereum",
    Polygon: "polygon",
    Bsc: "bsc",
} as const;
