/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of your contract.
 */
export type RegisterNftCollectionRequestContractType = "candy-machine" | "erc-721" | "erc-1155" | "thirdweb-drop";

export const RegisterNftCollectionRequestContractType = {
    CandyMachine: "candy-machine",
    Erc721: "erc-721",
    Erc1155: "erc-1155",
    ThirdwebDrop: "thirdweb-drop",
} as const;
