/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Crossmint from "../../../index";

export interface UpdateNftCollectionRequestMetadata {
    title: string;
    imageUrl: string;
    social?: Crossmint.UpdateNftCollectionRequestMetadataSocial;
}
