/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateNftCollectionRequestMetadataSocial {
    /** A link to your twitter page */
    twitter?: string;
    /** An invite link to your discord server */
    discord?: string;
}
