/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";

export const SignMessageResponse: core.serialization.ObjectSchema<
    serializers.SignMessageResponse.Raw,
    Crossmint.SignMessageResponse
> = core.serialization.object({
    signedMessage: core.serialization.string().optional(),
});

export declare namespace SignMessageResponse {
    interface Raw {
        signedMessage?: string | null;
    }
}
