/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CheckoutMintRequestCollection {
    /** Collection title */
    title: string;
    /** Collection description */
    description: string;
    /** Photo url */
    photo: string;
}
