/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";

export const CheckoutMintRequestCollection: core.serialization.ObjectSchema<
    serializers.CheckoutMintRequestCollection.Raw,
    Crossmint.CheckoutMintRequestCollection
> = core.serialization.object({
    title: core.serialization.string(),
    description: core.serialization.string(),
    photo: core.serialization.string(),
});

export declare namespace CheckoutMintRequestCollection {
    interface Raw {
        title: string;
        description: string;
        photo: string;
    }
}
