/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Crossmint from "../../../../api/index";
import * as core from "../../../../core";

export const CheckoutMintRequestRedirect: core.serialization.ObjectSchema<
    serializers.CheckoutMintRequestRedirect.Raw,
    Crossmint.CheckoutMintRequestRedirect
> = core.serialization.object({
    continue: core.serialization.string().optional(),
    cancel: core.serialization.string().optional(),
});

export declare namespace CheckoutMintRequestRedirect {
    interface Raw {
        continue?: string | null;
        cancel?: string | null;
    }
}
