/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EditRoyaltyInformationRequestRecipientsItem {
    /**
     * Address where the payments will be received.
     * Note: ENS addresses are not supported.
     */
    address?: string;
    /** Percentage of the sale price that will go to the recipient address. A basis point is a standard measure for percentages in finance. One basis point equals 1/100th of 1%, or 0.01%. */
    basisPoints?: number;
}
