/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const CrossmintEnvironment = {
    Staging: "https://staging.crossmint.com/api",
    Production: "https://www.crossmint.com/api",
} as const;

export type CrossmintEnvironment = typeof CrossmintEnvironment.Staging | typeof CrossmintEnvironment.Production;
